<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew C. Nowlin">

<title>Partisan vs Climate Cues and Public Opinion about Trump’s Actions on Energy</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="cue-actions_files/libs/clipboard/clipboard.min.js"></script>
<script src="cue-actions_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="cue-actions_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="cue-actions_files/libs/quarto-html/popper.min.js"></script>
<script src="cue-actions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="cue-actions_files/libs/quarto-html/anchor.min.js"></script>
<link href="cue-actions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cue-actions_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cue-actions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="cue-actions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="cue-actions_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="cue-actions.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="cue-actions.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Partisan vs Climate Cues and Public Opinion about Trump’s Actions on Energy</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Matthew C. Nowlin <a href="mailto:matthew.nowlin@uta.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Texas at Arlington
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<p><strong>Abstract</strong>: The second Trump administration has made strong and concerted efforts to shape energy production in the United States. In particular, the administration has moved to strengthen the fossil fuel industry and limit the use of renewable energy sources. Increasing the use of renewable sources is needed to address climate change. Yet, even with the connection to climate change, public support for renewable energy and policies supporting the development of renewable energy sources is not as polarized as support for climate change policies. However, the efforts of the Trump administration may serve to polarize public opinion on energy sources and the government’s role in shaping their availability. In this paper, I develop a pre-registered survey experiment to examine the polarization in support for several recent administration actions on energy when respondents are given a Trump cue, a climate change cue, and no cues. Specifically, I will survey 3,000 respondents recruited from Cloud Research, with 1,000 participants receiving a Trump cue, 1,000 participants receiving a climate cue, and 1,000 respondents in the control condition, who will receive no cue. Respondents in each condition will be asked about their level of support for several actions, including limiting tax credits for wind and solar projects, requiring coal plants to remain open, opening federal lands for coal leasing, cancelling a nearly complete offshore wind project, and shortening the timeline of regulatory approval for new nuclear plants. I compare the impacts of the Trump cue and climate cue on support for Trump administration actions across partisanship, ideology, and education level.</p>
<p><em>Paper prepared for submission to the Annual Meeting of the American Political Science Association, September 2026</em></p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Since returning to office for the second time, President Trump has sought to reestablish fossil fuels while sidelining renewable sources of energy. Early in his term, Trump declared a national energy emergency, directing federal agencies to use emergency statutory authorities to speed the development and authorization of energy projects and rescinding a number of prior climate-related executive orders <span class="citation" data-cites="columbiaTrumpDeclaresNational2025">(<a href="#ref-columbiaTrumpDeclaresNational2025" role="doc-biblioref">2025</a>)</span>. In the year that followed, the administration acted on several fronts to advance this agenda. The Department of the Treasury tightened the rules that wind and solar developers rely on to qualify for federal tax credits <span class="citation" data-cites="postTrumpAdministrationSlashes2025">(<a href="#ref-postTrumpAdministrationSlashes2025" role="doc-biblioref">2025</a>)</span>, while the Department of Energy repeatedly invoked emergency authority to keep aging coal plants running past their planned retirement dates, including plants in Michigan, Washington, Indiana, and Colorado <span class="citation" data-cites="cprTrumpAdministrationOrders2025">(<a href="#ref-cprTrumpAdministrationOrders2025" role="doc-biblioref">2025</a>)</span>. The Department of the Interior opened 13.1 million acres of federal land in Montana, North Dakota, and Wyoming for coal leasing <span class="citation" data-cites="doiInteriorUnleashesAmerican2025">(<a href="#ref-doiInteriorUnleashesAmerican2025" role="doc-biblioref">2025</a>)</span>, and separately halted construction on offshore wind projects along the East Coast, two of which were nearly complete <span class="citation" data-cites="nprTrumpAdministrationPauses2025">(<a href="#ref-nprTrumpAdministrationPauses2025" role="doc-biblioref">2025</a>)</span>. At the same time, the administration sought to accelerate nuclear energy development, directing the Nuclear Regulatory Commission to shorten its licensing review to under 18 months for new reactors <span class="citation" data-cites="doeKeyTakeawaysPresidents2025">(<a href="#ref-doeKeyTakeawaysPresidents2025" role="doc-biblioref">2025</a>)</span>.</p>
<p>For this project, I will use a survey experiment to examine the polarization in support for several recent administration actions on energy when respondents are given a Trump cue, a climate change cue, and no cues. Specifically, I will survey 3,000 respondents recruited from Cloud Research, with 1,000 participants receiving a Trump cue, 1,000 receiving a climate cue, and 1,000 in the control condition receiving no cue. Respondents in each condition will be asked about their level of support for several actions, including limiting tax credits for wind and solar projects, requiring coal plants to remain open, opening federal lands for coal leasing, cancelling a nearly complete offshore wind project, and shortening the timeline of regulatory approval for new nuclear plants.</p>
<p>I have several preregistered hypotheses regarding how respondents will respond to the Trump and climate cues based on political beliefs and education compared to those in the control group.</p>
</section>
<section id="polarization-on-energy-issues" class="level1">
<h1>Polarization on Energy Issues</h1>
<p>Public support for energy policy in the United States has grown increasingly polarized along partisan lines, even as aggregate support for many energy sources and policies has remained comparatively stable. Using data from three long-running national surveys spanning nearly two decades, Bergquist, Konisky, and Kotcher <span class="citation" data-cites="bergquistEnergyPolicyPublic2020">(<a href="#ref-bergquistEnergyPolicyPublic2020" role="doc-biblioref">2020</a>)</span> find that partisanship is the strongest predictor of energy policy preferences, with Republicans positioned nearly a full standard deviation from Democrats on a composite measure of support for an energy transition. This partisan gap has widened since 2008, even as support for expanding fossil fuel extraction has declined among the public overall. Notably, Bergquist et al. <span class="citation" data-cites="bergquistEnergyPolicyPublic2020">(<a href="#ref-bergquistEnergyPolicyPublic2020" role="doc-biblioref">2020</a>)</span> also show that when the costs of clean energy policies are made explicit, support declines by a similar magnitude for both Democrats and Republicans, suggesting that the partisan divide in energy opinion is not simply a function of differential cost sensitivity.</p>
<p>Underlying this partisan divide are different reasons for supporting, or opposing, a transition toward renewable energy. As noted by Gustafson et al. <span class="citation" data-cites="gustafsonRepublicansDemocratsDiffer2020">(<a href="#ref-gustafsonRepublicansDemocratsDiffer2020" role="doc-biblioref">2020</a>)</span>, Republicans’ support for renewable energy is driven more by considerations of economic costs and benefits, whereas Democrats’ support is driven more by concern about global warming. Using a nationally representative survey of registered voters, they found that Democrats most often cite “reduce global warming” as their single most important reason to support renewable energy (chosen by 33 percent of Democrats, compared to 7 percent of Republicans), while Republicans more often cite reasons tied to energy costs and energy independence. This divergence in underlying motivation is likely important for understanding how partisan and climate cues will separately shape support for energy actions: a cue that foregrounds cost or energy security is likely to resonate differently with Republicans than a cue that foregrounds climate change, and vice versa for Democrats.</p>
<p>Mayer <span class="citation" data-cites="mayerPartisanshipPoliticsEnergy2019">(<a href="#ref-mayerPartisanshipPoliticsEnergy2019" role="doc-biblioref">2019</a>)</span> argues that this partisan divide in energy attitudes reflects several distinct dimensions of partisanship rather than a single underlying mechanism. Specifically, Mayer <span class="citation" data-cites="mayerPartisanshipPoliticsEnergy2019">(<a href="#ref-mayerPartisanshipPoliticsEnergy2019" role="doc-biblioref">2019</a>)</span> proposes a four-part conceptual framework encompassing cue receptivity, expressive partisanship, negative partisanship, and performative partisanship, each of which may separately shape how citizens respond to information about energy and the energy transition. This framework is useful for anticipating how the cues examined in the current study, a Trump cue and a climate change cue, are likely to operate through different channels: a Trump cue is likely to activate expressive and cue-receptive partisanship among Republicans, while a climate cue is likely to activate the substantive climate concern already documented among Democrats.</p>
<p>In the next section, I discuss the theoretical mechanisms of partisan cue-taking in greater detail and describe how Trump and climate cues are likely to differentially shape support for Trump’s actions on energy.</p>
</section>
<section id="cues-and-cue-taking" class="level1">
<h1>Cues and Cue-Taking</h1>
<p>Partisan cues function as a heuristic that allows citizens to form opinions on complex policy issues without extensive information <span class="citation" data-cites="kamWhoToesParty2005 schaffnerPartisanHeuristicLowInformation2002">(<a href="#ref-kamWhoToesParty2005" role="doc-biblioref">Kam 2005</a>; <a href="#ref-schaffnerPartisanHeuristicLowInformation2002" role="doc-biblioref">Schaffner and Streb 2002</a>)</span>. Rather than evaluating the substantive merits of a policy, citizens often infer their own position from the position taken by their preferred party or its elites, a process that is well documented across a wide range of issues <span class="citation" data-cites="slothuusPoliticalPartiesMotivated2010 leeperPoliticalPartiesMotivated2014">(<a href="#ref-leeperPoliticalPartiesMotivated2014" role="doc-biblioref">Leeper and Slothuus 2014</a>; <a href="#ref-slothuusPoliticalPartiesMotivated2010" role="doc-biblioref">Slothuus and de Vreese 2010</a>)</span>. This cue-taking is best understood through the lens of motivated reasoning, wherein citizens process information in a way that protects and reinforces their prior partisan commitments rather than arriving at accuracy <span class="citation" data-cites="taberMotivatedSkepticismEvaluation2006 petersenMotivatedReasoningPolitical2013">(<a href="#ref-petersenMotivatedReasoningPolitical2013" role="doc-biblioref">Petersen et al. 2013</a>; <a href="#ref-taberMotivatedSkepticismEvaluation2006" role="doc-biblioref">Taber and Lodge 2006</a>)</span>. As elite polarization has intensified, party cues have become an increasingly powerful, and at times dominant, force in opinion formation, often overwhelming the effect of substantive policy information <span class="citation" data-cites="druckmanHowElitePartisan2013">(<a href="#ref-druckmanHowElitePartisan2013" role="doc-biblioref">Druckman, Peterson, and Slothuus 2013</a>)</span>.</p>
<p>Climate change and energy policy are particularly susceptible to this dynamic. As shown by Feldman and Hart <span class="citation" data-cites="feldmanClimateChangePolarizing2018">(<a href="#ref-feldmanClimateChangePolarizing2018" role="doc-biblioref">2018</a>)</span>, simply attaching a climate change frame or a cue from a Democratic source to an energy policy is often enough to depress support among Republicans, even when the underlying policy is left unchanged. Similarly, out-group cues from Democratic elites have been found to produce a durable backlash in climate skepticism among Republican identifiers <span class="citation" data-cites="merkleyPartyCuesNews2021">(<a href="#ref-merkleyPartyCuesNews2021" role="doc-biblioref">Merkley and Stecula 2021</a>)</span>, and partisan cue-taking extends to more recent and salient energy proposals, such as the Green New Deal <span class="citation" data-cites="mcconnellGreenNewDeal2022">(<a href="#ref-mcconnellGreenNewDeal2022" role="doc-biblioref">McConnell 2022</a>)</span>. These findings suggest that Trump cues and climate cues are likely to activate similar, but oppositely signed, partisan reactions to actions on energy: conservative Republicans are likely to become more supportive when an action is cued as coming from Trump or as countering climate change, whereas liberal Democrats are likely to become less supportive under the same cues.</p>
<p>Whether cue-taking of this kind is more pronounced among the less educated, however, is not as settled as the classic heuristics literature might suggest. Early accounts of the partisan heuristic emphasize that cue-taking substitutes for the cognitive effort required to process substantive information, implying that citizens with fewer cognitive resources, such as those without a college degree, should rely on party cues the most <span class="citation" data-cites="kamWhoToesParty2005">(<a href="#ref-kamWhoToesParty2005" role="doc-biblioref">Kam 2005</a>)</span>. Numeracy research supports this account: low-numeracy respondents rely more heavily on party cues, while high-numeracy respondents are more likely to update toward substantive policy information when it is available <span class="citation" data-cites="merolaNumeracyPersuasiveEffect2016">(<a href="#ref-merolaNumeracyPersuasiveEffect2016" role="doc-biblioref">Mérola and Hitt 2016</a>)</span>. Yet effortful thinking alone does not appear to be sufficient to reduce cue reliance; it is the availability of policy information, not cognitive effort per se, that weakens party cue effects <span class="citation" data-cites="tappinEstimatingCausalEffects2026">(<a href="#ref-tappinEstimatingCausalEffects2026" role="doc-biblioref">Tappin and McKay 2026</a>)</span>. Complicating the picture further, political sophistication and education are also associated with more effective motivated reasoning, meaning that better-informed citizens may process cue-congruent information more efficiently rather than less <span class="citation" data-cites="kahanIdeologyMotivatedReasoning2013">(<a href="#ref-kahanIdeologyMotivatedReasoning2013" role="doc-biblioref">Kahan 2013</a>)</span>. Bakker, Lelkes, and Malka <span class="citation" data-cites="bakkerUnderstandingPartisanCue2019">(<a href="#ref-bakkerUnderstandingPartisanCue2019" role="doc-biblioref">2019</a>)</span> similarly find that cue receptivity is not simply a function of bounded rationality but is strongest when cognitive resources are placed in service of expressive, identity-affirming reasoning. Consistent with this more conditional pattern, education has been found to amplify, rather than dampen, partisan polarization over climate change, particularly among conservatives <span class="citation" data-cites="hamiltonEducationPoliticsOpinions2011">(<a href="#ref-hamiltonEducationPoliticsOpinions2011" role="doc-biblioref">Hamilton 2011</a>)</span>. Together, this literature suggests that a college degree is likely to shape responsiveness to Trump and climate cues, but the direction of that relationship is less straightforward than the low-information heuristic model implies.</p>
<p>Additionally, a Trump cue may act differently than a typical partisan cue because of Trump’s purported strength among “working-class” voters, particularly white working class voters.</p>
<p>This pattern is consistent with a broader realignment of the American electorate along educational lines. Kitschelt and Rehm <span class="citation" data-cites="kitscheltSecularPartisanRealignment2019">(<a href="#ref-kitscheltSecularPartisanRealignment2019" role="doc-biblioref">2019</a>)</span> show that education, particularly when combined with income, has become one of the strongest predictors of white partisan support since the New Deal era, with non-college whites increasingly aligned with the Republican party. Zingher <span class="citation" data-cites="zingherDiplomaDivideEducational2022">(<a href="#ref-zingherDiplomaDivideEducational2022" role="doc-biblioref">2022</a>)</span> similarly documents a widening “diploma divide,” finding that educational attainment has become an increasingly strong predictor of both partisanship and vote choice since 2000, with less-educated counties trending Republican and more-educated counties trending Democratic. This divide reached a high point in the 2016 election: Sances <span class="citation" data-cites="sancesHowUnusualWas2019">(<a href="#ref-sancesHowUnusualWas2019" role="doc-biblioref">2019</a>)</span> finds that the education-party correlation was the strongest on record that year, and Morgan and Lee <span class="citation" data-cites="morganTrumpVotersWhite2018">(<a href="#ref-morganTrumpVotersWhite2018" role="doc-biblioref">2018</a>)</span> show that white working-class voters, including many who had supported Obama in 2012, were disproportionately likely to switch to Trump. Abramowitz and McCoy <span class="citation" data-cites="abramowitzUnitedStatesRacial2019">(<a href="#ref-abramowitzUnitedStatesRacial2019" role="doc-biblioref">2019</a>)</span> argue that this appeal was rooted in racial resentment, attracting strong support from white working-class voters while repelling many college-educated whites.</p>
<p>However, the centrality of the white working class to Trump’s coalition is not without dispute. Carnes and Lupu <span class="citation" data-cites="carnesWhiteWorkingClass2020">(<a href="#ref-carnesWhiteWorkingClass2020" role="doc-biblioref">2020</a>)</span> examine the available survey evidence and find that several common claims about the white working class in 2016, including the claim that this group was pivotal to Trump’s victory, are not well supported once turnout and longer-term partisan trends are taken into account. This unresolved debate is likely important for interpreting how a Trump cue operates: if support for Trump is substantially class-inflected rather than a straightforward partisan signal, a Trump cue may activate identity-based responses among non-college conservative Republicans and liberal Democrats that a generic partisan or climate cue would not. Whether this class-based moderation is actually present, however, is an empirical question that has not, to my knowledge, been tested directly in the context of cue-taking on energy policy.</p>
<section id="hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<blockquote class="blockquote">
<p>H1: Conservative Republicans who receive the Trump or climate change cue will be more supportive of Trump’s actions on energy than others</p>
</blockquote>
<blockquote class="blockquote">
<p>H2: Liberal Democrats who receive the Trump or climate change cue will be less supportive of Trump’s actions on energy than others</p>
</blockquote>
<blockquote class="blockquote">
<p>H3: Conservative Republicans without a college degree who receive the Trump cue will be more supportive of Trump’s actions on energy than others</p>
</blockquote>
<blockquote class="blockquote">
<p>H4: Liberal Democrats without a college degree who receive the Trump cue will be less supportive of Trump’s actions on energy than others</p>
</blockquote>
</section>
</section>
<section id="data-and-measures" class="level1">
<h1>Data and Measures</h1>
<p>The data for were obtained from a survey of a quota-based sample of US residents recruited through Cloud Research. The quota-based sampling approach using US Census data to help ensure representation across key demographic groups, including age, gender, and race. The survey was internet-based and administered using QuestionPro and was fielded from April 10 to April 15, 2026. Survey weights were applied to ensure that the sample was representative of the US population.</p>
<p>To measure the impact of the cues on support for Trump Administration actions on energy, respondents were randomly assigned to one of three conditions, including a Trump cue, a climate cue, and control condition with no cue. Overall, the groups were roughly equal, with the Trump cue, <em>n</em> = 1049, the climate cue, <em>n</em> = 1013, and the control, <em>n</em> = 1051, from the sample of <em>N</em> = 3113. The Trump cue identified the actions as being done by the <em>Trump Administration</em>, whereas the climate cue and the control conditions indicated the actions were by the <em>federal government</em>. The climate cue included a statement about concerns that climate scientists have about the impact of the actions on climate change. The question wording was as follows:</p>
<blockquote class="blockquote">
<p>Recently, the [<em>Trump Administration</em>/<em>Federal government</em>] took several actions to shape electricity generation in the U.S.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Climate cue</strong>: <em>Scientists are concerned that the actions associated with coal, wind, and solar energy will make climate change worse.</em></p>
</blockquote>
<blockquote class="blockquote">
<p>Using a scale of 1 to 5, where 1 means strongly oppose and 5 means strongly support, how do you feel about the following actions of the [<em>Trump Administration</em>/<em>Federal government</em>]? [The following were randomized]</p>
</blockquote>
<blockquote class="blockquote">
<ul>
<li>The [<em>Trump Administration</em>/<em>Federal government</em>] limiting the eligibility of wind and solar energy projects for federal tax credits</li>
<li>The [<em>Trump Administration</em>/<em>Federal government</em>] requiring coal plants that were set to retire to remain open</li>
<li>The [<em>Trump Administration</em>/<em>Federal government</em>] opening 13.1 million acres of federal land for coal leasing</li>
<li>The [<em>Trump Administration</em>/<em>Federal government</em>] cancelling an offshore wind project that was nearly complete</li>
<li>The [<em>Trump Administration</em>/<em>Federal government</em>] shortening the time it takes to approve and license the construction of new nuclear power plants</li>
</ul>
</blockquote>
<p>The main independent variables of interest are political beliefs, including conservative Republicans and liberal Democrats, with other political belief (moderate independents, conservative Democrats, liberal Republicans) as the excluded referent. College is dummy variable, 1 = completed a college degree, 0 = did not. <a href="#tbl-descriptives" class="quarto-xref">Table&nbsp;1</a> shows the descriptive statistics for each of the variables.</p>
<div class="cell">
<div id="tbl-descriptives" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Descriptive Statistics for Dependent and Independent Variables
</figcaption>
<div aria-describedby="tbl-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_td5zoar1ssvu0mwjqpwt = TinyTable.createTableFunctions("tinytable_td5zoar1ssvu0mwjqpwt");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '8', j: 1 }, { i: '8', j: 2 }, { i: '8', j: 3 }, { i: '8', j: 4 } ], css_id: 'tinytable_css_pso032u6a5pkaw8bv0kt',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 } ], css_id: 'tinytable_css_n53v2n3pg1jlt4tf6s9b',}, 
          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_v1cd5mdmlyqgcrsntfi4',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_td5zoar1ssvu0mwjqpwt.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_td5zoar1ssvu0mwjqpwt td.tinytable_css_pso032u6a5pkaw8bv0kt, #tinytable_td5zoar1ssvu0mwjqpwt th.tinytable_css_pso032u6a5pkaw8bv0kt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-size: 0.7em }
    #tinytable_td5zoar1ssvu0mwjqpwt td.tinytable_css_n53v2n3pg1jlt4tf6s9b, #tinytable_td5zoar1ssvu0mwjqpwt th.tinytable_css_n53v2n3pg1jlt4tf6s9b { font-size: 0.7em }
    #tinytable_td5zoar1ssvu0mwjqpwt td.tinytable_css_v1cd5mdmlyqgcrsntfi4, #tinytable_td5zoar1ssvu0mwjqpwt th.tinytable_css_v1cd5mdmlyqgcrsntfi4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-size: 0.7em }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_td5zoar1ssvu0mwjqpwt" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1">Variable</th>
                <th scope="col" data-row="0" data-col="2">Range</th>
                <th scope="col" data-row="0" data-col="3">Mean</th>
                <th scope="col" data-row="0" data-col="4">SD</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Tax Credits</td>
                  <td data-row="1" data-col="2">1-5</td>
                  <td data-row="1" data-col="3">2.26</td>
                  <td data-row="1" data-col="4">1.28</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1">Coal Open</td>
                  <td data-row="2" data-col="2">1-5</td>
                  <td data-row="2" data-col="3">2.48</td>
                  <td data-row="2" data-col="4">1.25</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Coal Leasing</td>
                  <td data-row="3" data-col="2">1-5</td>
                  <td data-row="3" data-col="3">2.39</td>
                  <td data-row="3" data-col="4">1.28</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1">Cancel Wind</td>
                  <td data-row="4" data-col="2">1-5</td>
                  <td data-row="4" data-col="3">2.09</td>
                  <td data-row="4" data-col="4">1.25</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Nuclear</td>
                  <td data-row="5" data-col="2">1-5</td>
                  <td data-row="5" data-col="3">2.97</td>
                  <td data-row="5" data-col="4">1.33</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1">Cons. Republican</td>
                  <td data-row="6" data-col="2">0-1</td>
                  <td data-row="6" data-col="3">0.40</td>
                  <td data-row="6" data-col="4">0.49</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Lib. Democrat</td>
                  <td data-row="7" data-col="2">0-1</td>
                  <td data-row="7" data-col="3">0.37</td>
                  <td data-row="7" data-col="4">0.48</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1">College</td>
                  <td data-row="8" data-col="2">0-1</td>
                  <td data-row="8" data-col="3">0.36</td>
                  <td data-row="8" data-col="4">0.48</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</figure>
</div>
</div>
<p>In terms of support for the various actions, they each seem to hover around the mid-point of the 1 to 5 scale with cancelling nearly complete wind projects showing the least support at 2.09 and reducing nuclear energy regulations showing the most at 2.97.</p>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>The first two hypotheses posited that political beliefs will shape the impact of the Trump and climate cues, with conservative Republicans expected to respond to the Trump and climate cues with more support for Trump actions and liberal Democrats expected to respond with less support. <a href="#fig-identity" class="quarto-xref">Figure&nbsp;1</a> shows the results of the OLS models for cue condition and political beliefs.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-identity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-identity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Predicted Support by Cue Condition and Political Beliefs
</figcaption>
<div aria-describedby="fig-identity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cue-actions_files/figure-html/fig-identity-1.png" class="img-fluid figure-img" width="1056">
</div>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-identity" class="quarto-xref">Figure&nbsp;1</a>, for conservative Republicans, the Trump cue significantly increased their support for opening federal lands to coal leasing and for shortening approval for nuclear power construction. Additionally, support for keeping coal plants open and cancelling the offshore wind projects were significant at <em>p</em>&lt;0.10 in the Trump condition. However, the Trump cue did not influence support for eliminating federal tax credits; rather, the climate cue lead to a <em>decrease</em> in support for eliminating the tax credits among conservative Republicans. Otherwise, the climate cue did not have any effects for Republicans, contrary to expectations.</p>
<p>Liberal Democrats were largely unresponsive to either the Trump cue or the climate cue, compared to those in the control condition. The climate cue reduced support for eliminating the tax credits at <em>p</em>&lt;0.10.</p>
<p>Next, I examine the hypotheses regarding the effect of education and cues. The results are shown in <a href="#fig-college" class="quarto-xref">Figure&nbsp;2</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-college" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-college-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Predicted Support by Trump Cue and College Degree, Conservative Republicans and Liberal Democrats
</figcaption>
<div aria-describedby="fig-college-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cue-actions_files/figure-html/fig-college-1.png" class="img-fluid figure-img" width="1056">
</div>
</figure>
</div>
</div>
</div>
<p>As can be seen, there were no differences in support based on education level, meaning that those without a college degree were no more influenced the Trump cue than those without a degree. This finding held for Republicans and Democrats.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Overall, the clearest evidence is for H1: the Trump cue, but not the climate cue, increased conservative Republican support for four of the five actions (coal leasing and nuclear licensing significantly; keeping coal plants open and cancelling the offshore wind project marginally). There is no reliable evidence that either cue suppressed liberal Democrats’ support (H2), or that education moderated the Trump cue’s effect on either group (H3, H4). Dropping the Trump-approval control leaves these conclusions materially unchanged.</p>
<p>As an exploratory check (not preregistered), I also tested whether education moderates the <em>climate</em> cue’s effect, adding climate.cue:college and its interactions with conRep and libDem to a separate model (<a href="#tbl-results-explore" class="quarto-xref">Table&nbsp;3</a>). None of these terms approached significance in any of the five models (all <em>p</em> &gt; .20), so, unlike the weak evidence for the Trump cue, there is no indication that education conditions the climate cue’s effect.</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<div style="page-break-after: always;"></div>
</section>
<section id="appendix" class="level1">
<h1>Appendix</h1>
<div class="cell">
<div id="tbl-results" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Weighted OLS Models of Support for Trump’s Energy Actions
</figcaption>
<div aria-describedby="tbl-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_g2heor2qamaewtrwt6s9 = TinyTable.createTableFunctions("tinytable_g2heor2qamaewtrwt6s9");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '32', j: 2 }, { i: '32', j: 3 }, { i: '32', j: 4 }, { i: '32', j: 5 }, { i: '32', j: 6 } ], css_id: 'tinytable_css_worgqzq0my6ggwhjsb2c',}, 
          { positions: [ { i: '30', j: 2 }, { i: '30', j: 3 }, { i: '30', j: 4 }, { i: '30', j: 5 }, { i: '30', j: 6 } ], css_id: 'tinytable_css_htv9712j2b6g1d1rswhi',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '21', j: 2 }, { i: '22', j: 2 }, { i: '23', j: 2 }, { i: '24', j: 2 }, { i: '25', j: 2 }, { i: '26', j: 2 }, { i: '27', j: 2 }, { i: '28', j: 2 }, { i: '29', j: 2 }, { i: '31', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '16', j: 3 }, { i: '17', j: 3 }, { i: '18', j: 3 }, { i: '19', j: 3 }, { i: '20', j: 3 }, { i: '21', j: 3 }, { i: '22', j: 3 }, { i: '23', j: 3 }, { i: '24', j: 3 }, { i: '25', j: 3 }, { i: '26', j: 3 }, { i: '27', j: 3 }, { i: '28', j: 3 }, { i: '29', j: 3 }, { i: '31', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '13', j: 4 }, { i: '14', j: 4 }, { i: '15', j: 4 }, { i: '16', j: 4 }, { i: '17', j: 4 }, { i: '18', j: 4 }, { i: '19', j: 4 }, { i: '20', j: 4 }, { i: '21', j: 4 }, { i: '22', j: 4 }, { i: '23', j: 4 }, { i: '24', j: 4 }, { i: '25', j: 4 }, { i: '26', j: 4 }, { i: '27', j: 4 }, { i: '28', j: 4 }, { i: '29', j: 4 }, { i: '31', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '7', j: 5 }, { i: '8', j: 5 }, { i: '9', j: 5 }, { i: '10', j: 5 }, { i: '11', j: 5 }, { i: '12', j: 5 }, { i: '13', j: 5 }, { i: '14', j: 5 }, { i: '15', j: 5 }, { i: '16', j: 5 }, { i: '17', j: 5 }, { i: '18', j: 5 }, { i: '19', j: 5 }, { i: '20', j: 5 }, { i: '21', j: 5 }, { i: '22', j: 5 }, { i: '23', j: 5 }, { i: '24', j: 5 }, { i: '25', j: 5 }, { i: '26', j: 5 }, { i: '27', j: 5 }, { i: '28', j: 5 }, { i: '29', j: 5 }, { i: '31', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '3', j: 6 }, { i: '4', j: 6 }, { i: '5', j: 6 }, { i: '6', j: 6 }, { i: '7', j: 6 }, { i: '8', j: 6 }, { i: '9', j: 6 }, { i: '10', j: 6 }, { i: '11', j: 6 }, { i: '12', j: 6 }, { i: '13', j: 6 }, { i: '14', j: 6 }, { i: '15', j: 6 }, { i: '16', j: 6 }, { i: '17', j: 6 }, { i: '18', j: 6 }, { i: '19', j: 6 }, { i: '20', j: 6 }, { i: '21', j: 6 }, { i: '22', j: 6 }, { i: '23', j: 6 }, { i: '24', j: 6 }, { i: '25', j: 6 }, { i: '26', j: 6 }, { i: '27', j: 6 }, { i: '28', j: 6 }, { i: '29', j: 6 }, { i: '31', j: 6 } ], css_id: 'tinytable_css_5jr3vo7ck2ub8ufc7u8t',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_4mfcbzm9996d4uzq2zed',}, 
          { positions: [ { i: '32', j: 1 } ], css_id: 'tinytable_css_cp6rm0xk6vc8xvp4nyq2',}, 
          { positions: [ { i: '30', j: 1 } ], css_id: 'tinytable_css_ezq9wkfozh54h4jqsrpo',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 }, { i: '21', j: 1 }, { i: '22', j: 1 }, { i: '23', j: 1 }, { i: '24', j: 1 }, { i: '25', j: 1 }, { i: '26', j: 1 }, { i: '27', j: 1 }, { i: '28', j: 1 }, { i: '29', j: 1 }, { i: '31', j: 1 } ], css_id: 'tinytable_css_6biuzihukhrqokzhpc66',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_yrnhwyi1giy35on95bq5',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_g2heor2qamaewtrwt6s9.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_g2heor2qamaewtrwt6s9 td.tinytable_css_worgqzq0my6ggwhjsb2c, #tinytable_g2heor2qamaewtrwt6s9 th.tinytable_css_worgqzq0my6ggwhjsb2c {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center; font-size: 0.7em }
    #tinytable_g2heor2qamaewtrwt6s9 td.tinytable_css_htv9712j2b6g1d1rswhi, #tinytable_g2heor2qamaewtrwt6s9 th.tinytable_css_htv9712j2b6g1d1rswhi {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center; font-size: 0.7em }
    #tinytable_g2heor2qamaewtrwt6s9 td.tinytable_css_5jr3vo7ck2ub8ufc7u8t, #tinytable_g2heor2qamaewtrwt6s9 th.tinytable_css_5jr3vo7ck2ub8ufc7u8t { text-align: center; font-size: 0.7em }
    #tinytable_g2heor2qamaewtrwt6s9 td.tinytable_css_4mfcbzm9996d4uzq2zed, #tinytable_g2heor2qamaewtrwt6s9 th.tinytable_css_4mfcbzm9996d4uzq2zed {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center; font-size: 0.7em }
    #tinytable_g2heor2qamaewtrwt6s9 td.tinytable_css_cp6rm0xk6vc8xvp4nyq2, #tinytable_g2heor2qamaewtrwt6s9 th.tinytable_css_cp6rm0xk6vc8xvp4nyq2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left; font-size: 0.7em }
    #tinytable_g2heor2qamaewtrwt6s9 td.tinytable_css_ezq9wkfozh54h4jqsrpo, #tinytable_g2heor2qamaewtrwt6s9 th.tinytable_css_ezq9wkfozh54h4jqsrpo {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left; font-size: 0.7em }
    #tinytable_g2heor2qamaewtrwt6s9 td.tinytable_css_6biuzihukhrqokzhpc66, #tinytable_g2heor2qamaewtrwt6s9 th.tinytable_css_6biuzihukhrqokzhpc66 { text-align: left; font-size: 0.7em }
    #tinytable_g2heor2qamaewtrwt6s9 td.tinytable_css_yrnhwyi1giy35on95bq5, #tinytable_g2heor2qamaewtrwt6s9 th.tinytable_css_yrnhwyi1giy35on95bq5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left; font-size: 0.7em }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_g2heor2qamaewtrwt6s9" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Tax Credits</th>
                <th scope="col" data-row="0" data-col="3">Coal Open</th>
                <th scope="col" data-row="0" data-col="4">Coal Leasing</th>
                <th scope="col" data-row="0" data-col="5">Cancel Wind</th>
                <th scope="col" data-row="0" data-col="6">Nuclear</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="6">† p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr>
<tr><td colspan="6">Survey-weighted OLS (svyglm). Reference categories: control condition, moderate/other political identity, no college degree.</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Trump Cue</td>
                  <td data-row="1" data-col="2">-0.035</td>
                  <td data-row="1" data-col="3">-0.074</td>
                  <td data-row="1" data-col="4">-0.115</td>
                  <td data-row="1" data-col="5">-0.037</td>
                  <td data-row="1" data-col="6">-0.306†</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.135)</td>
                  <td data-row="2" data-col="3">(0.141)</td>
                  <td data-row="2" data-col="4">(0.146)</td>
                  <td data-row="2" data-col="5">(0.115)</td>
                  <td data-row="2" data-col="6">(0.166)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Climate Cue</td>
                  <td data-row="3" data-col="2">0.320**</td>
                  <td data-row="3" data-col="3">0.210†</td>
                  <td data-row="3" data-col="4">0.090</td>
                  <td data-row="3" data-col="5">0.169</td>
                  <td data-row="3" data-col="6">-0.089</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.117)</td>
                  <td data-row="4" data-col="3">(0.117)</td>
                  <td data-row="4" data-col="4">(0.112)</td>
                  <td data-row="4" data-col="5">(0.105)</td>
                  <td data-row="4" data-col="6">(0.124)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Cons. Republican</td>
                  <td data-row="5" data-col="2">1.119***</td>
                  <td data-row="5" data-col="3">0.968***</td>
                  <td data-row="5" data-col="4">0.933***</td>
                  <td data-row="5" data-col="5">1.115***</td>
                  <td data-row="5" data-col="6">0.555***</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.133)</td>
                  <td data-row="6" data-col="3">(0.131)</td>
                  <td data-row="6" data-col="4">(0.128)</td>
                  <td data-row="6" data-col="5">(0.130)</td>
                  <td data-row="6" data-col="6">(0.151)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Lib. Democrat</td>
                  <td data-row="7" data-col="2">-0.491***</td>
                  <td data-row="7" data-col="3">-0.649***</td>
                  <td data-row="7" data-col="4">-0.617***</td>
                  <td data-row="7" data-col="5">-0.328***</td>
                  <td data-row="7" data-col="6">-0.376**</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.108)</td>
                  <td data-row="8" data-col="3">(0.114)</td>
                  <td data-row="8" data-col="4">(0.112)</td>
                  <td data-row="8" data-col="5">(0.094)</td>
                  <td data-row="8" data-col="6">(0.134)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">College</td>
                  <td data-row="9" data-col="2">0.178</td>
                  <td data-row="9" data-col="3">0.086</td>
                  <td data-row="9" data-col="4">0.041</td>
                  <td data-row="9" data-col="5">0.280*</td>
                  <td data-row="9" data-col="6">0.315**</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.114)</td>
                  <td data-row="10" data-col="3">(0.113)</td>
                  <td data-row="10" data-col="4">(0.109)</td>
                  <td data-row="10" data-col="5">(0.113)</td>
                  <td data-row="10" data-col="6">(0.114)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">Trump x ConRep</td>
                  <td data-row="11" data-col="2">0.319</td>
                  <td data-row="11" data-col="3">0.348†</td>
                  <td data-row="11" data-col="4">0.456*</td>
                  <td data-row="11" data-col="5">0.348†</td>
                  <td data-row="11" data-col="6">0.506*</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.209)</td>
                  <td data-row="12" data-col="3">(0.196)</td>
                  <td data-row="12" data-col="4">(0.202)</td>
                  <td data-row="12" data-col="5">(0.209)</td>
                  <td data-row="12" data-col="6">(0.235)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Climate x ConRep</td>
                  <td data-row="13" data-col="2">-0.442**</td>
                  <td data-row="13" data-col="3">-0.239</td>
                  <td data-row="13" data-col="4">-0.091</td>
                  <td data-row="13" data-col="5">-0.212</td>
                  <td data-row="13" data-col="6">0.142</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1"></td>
                  <td data-row="14" data-col="2">(0.167)</td>
                  <td data-row="14" data-col="3">(0.156)</td>
                  <td data-row="14" data-col="4">(0.158)</td>
                  <td data-row="14" data-col="5">(0.164)</td>
                  <td data-row="14" data-col="6">(0.176)</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">Trump x LibDem</td>
                  <td data-row="15" data-col="2">-0.067</td>
                  <td data-row="15" data-col="3">-0.068</td>
                  <td data-row="15" data-col="4">-0.071</td>
                  <td data-row="15" data-col="5">-0.130</td>
                  <td data-row="15" data-col="6">-0.155</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1"></td>
                  <td data-row="16" data-col="2">(0.156)</td>
                  <td data-row="16" data-col="3">(0.166)</td>
                  <td data-row="16" data-col="4">(0.170)</td>
                  <td data-row="16" data-col="5">(0.132)</td>
                  <td data-row="16" data-col="6">(0.204)</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">Climate x LibDem</td>
                  <td data-row="17" data-col="2">-0.238†</td>
                  <td data-row="17" data-col="3">-0.170</td>
                  <td data-row="17" data-col="4">-0.077</td>
                  <td data-row="17" data-col="5">-0.147</td>
                  <td data-row="17" data-col="6">0.098</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1"></td>
                  <td data-row="18" data-col="2">(0.136)</td>
                  <td data-row="18" data-col="3">(0.138)</td>
                  <td data-row="18" data-col="4">(0.132)</td>
                  <td data-row="18" data-col="5">(0.120)</td>
                  <td data-row="18" data-col="6">(0.153)</td>
                </tr>
                <tr>
                  <td data-row="19" data-col="1">Trump x College</td>
                  <td data-row="19" data-col="2">0.064</td>
                  <td data-row="19" data-col="3">0.032</td>
                  <td data-row="19" data-col="4">0.119</td>
                  <td data-row="19" data-col="5">0.098</td>
                  <td data-row="19" data-col="6">0.140</td>
                </tr>
                <tr>
                  <td data-row="20" data-col="1"></td>
                  <td data-row="20" data-col="2">(0.191)</td>
                  <td data-row="20" data-col="3">(0.186)</td>
                  <td data-row="20" data-col="4">(0.198)</td>
                  <td data-row="20" data-col="5">(0.183)</td>
                  <td data-row="20" data-col="6">(0.203)</td>
                </tr>
                <tr>
                  <td data-row="21" data-col="1">College x ConRep</td>
                  <td data-row="21" data-col="2">-0.230</td>
                  <td data-row="21" data-col="3">-0.206</td>
                  <td data-row="21" data-col="4">-0.169</td>
                  <td data-row="21" data-col="5">-0.342*</td>
                  <td data-row="21" data-col="6">-0.309†</td>
                </tr>
                <tr>
                  <td data-row="22" data-col="1"></td>
                  <td data-row="22" data-col="2">(0.162)</td>
                  <td data-row="22" data-col="3">(0.149)</td>
                  <td data-row="22" data-col="4">(0.152)</td>
                  <td data-row="22" data-col="5">(0.167)</td>
                  <td data-row="22" data-col="6">(0.165)</td>
                </tr>
                <tr>
                  <td data-row="23" data-col="1">College x LibDem</td>
                  <td data-row="23" data-col="2">-0.279*</td>
                  <td data-row="23" data-col="3">-0.161</td>
                  <td data-row="23" data-col="4">-0.172</td>
                  <td data-row="23" data-col="5">-0.410***</td>
                  <td data-row="23" data-col="6">-0.332*</td>
                </tr>
                <tr>
                  <td data-row="24" data-col="1"></td>
                  <td data-row="24" data-col="2">(0.130)</td>
                  <td data-row="24" data-col="3">(0.132)</td>
                  <td data-row="24" data-col="4">(0.126)</td>
                  <td data-row="24" data-col="5">(0.124)</td>
                  <td data-row="24" data-col="6">(0.143)</td>
                </tr>
                <tr>
                  <td data-row="25" data-col="1">Trump x ConRep x College</td>
                  <td data-row="25" data-col="2">-0.414</td>
                  <td data-row="25" data-col="3">-0.096</td>
                  <td data-row="25" data-col="4">-0.184</td>
                  <td data-row="25" data-col="5">-0.401</td>
                  <td data-row="25" data-col="6">-0.053</td>
                </tr>
                <tr>
                  <td data-row="26" data-col="1"></td>
                  <td data-row="26" data-col="2">(0.283)</td>
                  <td data-row="26" data-col="3">(0.258)</td>
                  <td data-row="26" data-col="4">(0.277)</td>
                  <td data-row="26" data-col="5">(0.293)</td>
                  <td data-row="26" data-col="6">(0.290)</td>
                </tr>
                <tr>
                  <td data-row="27" data-col="1">Trump x LibDem x College</td>
                  <td data-row="27" data-col="2">-0.011</td>
                  <td data-row="27" data-col="3">-0.040</td>
                  <td data-row="27" data-col="4">-0.104</td>
                  <td data-row="27" data-col="5">0.026</td>
                  <td data-row="27" data-col="6">0.029</td>
                </tr>
                <tr>
                  <td data-row="28" data-col="1"></td>
                  <td data-row="28" data-col="2">(0.213)</td>
                  <td data-row="28" data-col="3">(0.214)</td>
                  <td data-row="28" data-col="4">(0.222)</td>
                  <td data-row="28" data-col="5">(0.199)</td>
                  <td data-row="28" data-col="6">(0.249)</td>
                </tr>
                <tr>
                  <td data-row="29" data-col="1">Intercept</td>
                  <td data-row="29" data-col="2">1.983***</td>
                  <td data-row="29" data-col="3">2.342***</td>
                  <td data-row="29" data-col="4">2.267***</td>
                  <td data-row="29" data-col="5">1.756***</td>
                  <td data-row="29" data-col="6">2.911***</td>
                </tr>
                <tr>
                  <td data-row="30" data-col="1"></td>
                  <td data-row="30" data-col="2">(0.093)</td>
                  <td data-row="30" data-col="3">(0.097)</td>
                  <td data-row="30" data-col="4">(0.093)</td>
                  <td data-row="30" data-col="5">(0.080)</td>
                  <td data-row="30" data-col="6">(0.107)</td>
                </tr>
                <tr>
                  <td data-row="31" data-col="1">Num.Obs.</td>
                  <td data-row="31" data-col="2">3113</td>
                  <td data-row="31" data-col="3">3113</td>
                  <td data-row="31" data-col="4">3113</td>
                  <td data-row="31" data-col="5">3113</td>
                  <td data-row="31" data-col="6">3113</td>
                </tr>
                <tr>
                  <td data-row="32" data-col="1">R2</td>
                  <td data-row="32" data-col="2">0.330</td>
                  <td data-row="32" data-col="3">0.368</td>
                  <td data-row="32" data-col="4">0.358</td>
                  <td data-row="32" data-col="5">0.314</td>
                  <td data-row="32" data-col="6">0.163</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-results-explore" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-results-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Exploratory Model: Climate Cue x Education (Not Preregistered)
</figcaption>
<div aria-describedby="tbl-results-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_z6tt420r57no4g1bcs51 = TinyTable.createTableFunctions("tinytable_z6tt420r57no4g1bcs51");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '38', j: 2 }, { i: '38', j: 3 }, { i: '38', j: 4 }, { i: '38', j: 5 }, { i: '38', j: 6 } ], css_id: 'tinytable_css_1u0oo1pua8scy05hyu11',}, 
          { positions: [ { i: '36', j: 2 }, { i: '36', j: 3 }, { i: '36', j: 4 }, { i: '36', j: 5 }, { i: '36', j: 6 } ], css_id: 'tinytable_css_zlm4jz0j1xuimcgxlu6t',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '21', j: 2 }, { i: '22', j: 2 }, { i: '23', j: 2 }, { i: '24', j: 2 }, { i: '25', j: 2 }, { i: '26', j: 2 }, { i: '27', j: 2 }, { i: '28', j: 2 }, { i: '29', j: 2 }, { i: '30', j: 2 }, { i: '31', j: 2 }, { i: '32', j: 2 }, { i: '33', j: 2 }, { i: '34', j: 2 }, { i: '35', j: 2 }, { i: '37', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '16', j: 3 }, { i: '17', j: 3 }, { i: '18', j: 3 }, { i: '19', j: 3 }, { i: '20', j: 3 }, { i: '21', j: 3 }, { i: '22', j: 3 }, { i: '23', j: 3 }, { i: '24', j: 3 }, { i: '25', j: 3 }, { i: '26', j: 3 }, { i: '27', j: 3 }, { i: '28', j: 3 }, { i: '29', j: 3 }, { i: '30', j: 3 }, { i: '31', j: 3 }, { i: '32', j: 3 }, { i: '33', j: 3 }, { i: '34', j: 3 }, { i: '35', j: 3 }, { i: '37', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '13', j: 4 }, { i: '14', j: 4 }, { i: '15', j: 4 }, { i: '16', j: 4 }, { i: '17', j: 4 }, { i: '18', j: 4 }, { i: '19', j: 4 }, { i: '20', j: 4 }, { i: '21', j: 4 }, { i: '22', j: 4 }, { i: '23', j: 4 }, { i: '24', j: 4 }, { i: '25', j: 4 }, { i: '26', j: 4 }, { i: '27', j: 4 }, { i: '28', j: 4 }, { i: '29', j: 4 }, { i: '30', j: 4 }, { i: '31', j: 4 }, { i: '32', j: 4 }, { i: '33', j: 4 }, { i: '34', j: 4 }, { i: '35', j: 4 }, { i: '37', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '7', j: 5 }, { i: '8', j: 5 }, { i: '9', j: 5 }, { i: '10', j: 5 }, { i: '11', j: 5 }, { i: '12', j: 5 }, { i: '13', j: 5 }, { i: '14', j: 5 }, { i: '15', j: 5 }, { i: '16', j: 5 }, { i: '17', j: 5 }, { i: '18', j: 5 }, { i: '19', j: 5 }, { i: '20', j: 5 }, { i: '21', j: 5 }, { i: '22', j: 5 }, { i: '23', j: 5 }, { i: '24', j: 5 }, { i: '25', j: 5 }, { i: '26', j: 5 }, { i: '27', j: 5 }, { i: '28', j: 5 }, { i: '29', j: 5 }, { i: '30', j: 5 }, { i: '31', j: 5 }, { i: '32', j: 5 }, { i: '33', j: 5 }, { i: '34', j: 5 }, { i: '35', j: 5 }, { i: '37', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '3', j: 6 }, { i: '4', j: 6 }, { i: '5', j: 6 }, { i: '6', j: 6 }, { i: '7', j: 6 }, { i: '8', j: 6 }, { i: '9', j: 6 }, { i: '10', j: 6 }, { i: '11', j: 6 }, { i: '12', j: 6 }, { i: '13', j: 6 }, { i: '14', j: 6 }, { i: '15', j: 6 }, { i: '16', j: 6 }, { i: '17', j: 6 }, { i: '18', j: 6 }, { i: '19', j: 6 }, { i: '20', j: 6 }, { i: '21', j: 6 }, { i: '22', j: 6 }, { i: '23', j: 6 }, { i: '24', j: 6 }, { i: '25', j: 6 }, { i: '26', j: 6 }, { i: '27', j: 6 }, { i: '28', j: 6 }, { i: '29', j: 6 }, { i: '30', j: 6 }, { i: '31', j: 6 }, { i: '32', j: 6 }, { i: '33', j: 6 }, { i: '34', j: 6 }, { i: '35', j: 6 }, { i: '37', j: 6 } ], css_id: 'tinytable_css_oxm9m2f6iid4xv9t897h',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_v3doi7ns9l19s1slduc4',}, 
          { positions: [ { i: '38', j: 1 } ], css_id: 'tinytable_css_tndubp3bsuyunotejiwi',}, 
          { positions: [ { i: '36', j: 1 } ], css_id: 'tinytable_css_nzrpoxwpptcstsa9gti2',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 }, { i: '21', j: 1 }, { i: '22', j: 1 }, { i: '23', j: 1 }, { i: '24', j: 1 }, { i: '25', j: 1 }, { i: '26', j: 1 }, { i: '27', j: 1 }, { i: '28', j: 1 }, { i: '29', j: 1 }, { i: '30', j: 1 }, { i: '31', j: 1 }, { i: '32', j: 1 }, { i: '33', j: 1 }, { i: '34', j: 1 }, { i: '35', j: 1 }, { i: '37', j: 1 } ], css_id: 'tinytable_css_ypojhtkg1vel0mz2crgp',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_6em9rjbw906htxou3stl',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_z6tt420r57no4g1bcs51.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_z6tt420r57no4g1bcs51 td.tinytable_css_1u0oo1pua8scy05hyu11, #tinytable_z6tt420r57no4g1bcs51 th.tinytable_css_1u0oo1pua8scy05hyu11 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center; font-size: 0.7em }
    #tinytable_z6tt420r57no4g1bcs51 td.tinytable_css_zlm4jz0j1xuimcgxlu6t, #tinytable_z6tt420r57no4g1bcs51 th.tinytable_css_zlm4jz0j1xuimcgxlu6t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center; font-size: 0.7em }
    #tinytable_z6tt420r57no4g1bcs51 td.tinytable_css_oxm9m2f6iid4xv9t897h, #tinytable_z6tt420r57no4g1bcs51 th.tinytable_css_oxm9m2f6iid4xv9t897h { text-align: center; font-size: 0.7em }
    #tinytable_z6tt420r57no4g1bcs51 td.tinytable_css_v3doi7ns9l19s1slduc4, #tinytable_z6tt420r57no4g1bcs51 th.tinytable_css_v3doi7ns9l19s1slduc4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center; font-size: 0.7em }
    #tinytable_z6tt420r57no4g1bcs51 td.tinytable_css_tndubp3bsuyunotejiwi, #tinytable_z6tt420r57no4g1bcs51 th.tinytable_css_tndubp3bsuyunotejiwi {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left; font-size: 0.7em }
    #tinytable_z6tt420r57no4g1bcs51 td.tinytable_css_nzrpoxwpptcstsa9gti2, #tinytable_z6tt420r57no4g1bcs51 th.tinytable_css_nzrpoxwpptcstsa9gti2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left; font-size: 0.7em }
    #tinytable_z6tt420r57no4g1bcs51 td.tinytable_css_ypojhtkg1vel0mz2crgp, #tinytable_z6tt420r57no4g1bcs51 th.tinytable_css_ypojhtkg1vel0mz2crgp { text-align: left; font-size: 0.7em }
    #tinytable_z6tt420r57no4g1bcs51 td.tinytable_css_6em9rjbw906htxou3stl, #tinytable_z6tt420r57no4g1bcs51 th.tinytable_css_6em9rjbw906htxou3stl {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left; font-size: 0.7em }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_z6tt420r57no4g1bcs51" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Tax Credits</th>
                <th scope="col" data-row="0" data-col="3">Coal Open</th>
                <th scope="col" data-row="0" data-col="4">Coal Leasing</th>
                <th scope="col" data-row="0" data-col="5">Cancel Wind</th>
                <th scope="col" data-row="0" data-col="6">Nuclear</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="6">† p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr>
<tr><td colspan="6">Survey-weighted OLS (svyglm). Exploratory model adding climate.cue:college and its interactions with conRep/libDem to the preregistered H1-H4 specification; not used for the preregistered hypothesis tests.</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Trump Cue</td>
                  <td data-row="1" data-col="2">-0.003</td>
                  <td data-row="1" data-col="3">-0.043</td>
                  <td data-row="1" data-col="4">-0.080</td>
                  <td data-row="1" data-col="5">-0.025</td>
                  <td data-row="1" data-col="6">-0.318†</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.143)</td>
                  <td data-row="2" data-col="3">(0.150)</td>
                  <td data-row="2" data-col="4">(0.154)</td>
                  <td data-row="2" data-col="5">(0.120)</td>
                  <td data-row="2" data-col="6">(0.177)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Climate Cue</td>
                  <td data-row="3" data-col="2">0.385*</td>
                  <td data-row="3" data-col="3">0.273†</td>
                  <td data-row="3" data-col="4">0.163</td>
                  <td data-row="3" data-col="5">0.194</td>
                  <td data-row="3" data-col="6">-0.114</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.156)</td>
                  <td data-row="4" data-col="3">(0.156)</td>
                  <td data-row="4" data-col="4">(0.149)</td>
                  <td data-row="4" data-col="5">(0.127)</td>
                  <td data-row="4" data-col="6">(0.172)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Cons. Republican</td>
                  <td data-row="5" data-col="2">1.104***</td>
                  <td data-row="5" data-col="3">0.973***</td>
                  <td data-row="5" data-col="4">0.921***</td>
                  <td data-row="5" data-col="5">1.093***</td>
                  <td data-row="5" data-col="6">0.481**</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.149)</td>
                  <td data-row="6" data-col="3">(0.150)</td>
                  <td data-row="6" data-col="4">(0.144)</td>
                  <td data-row="6" data-col="5">(0.144)</td>
                  <td data-row="6" data-col="6">(0.172)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Lib. Democrat</td>
                  <td data-row="7" data-col="2">-0.502***</td>
                  <td data-row="7" data-col="3">-0.627***</td>
                  <td data-row="7" data-col="4">-0.597***</td>
                  <td data-row="7" data-col="5">-0.330**</td>
                  <td data-row="7" data-col="6">-0.424**</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.121)</td>
                  <td data-row="8" data-col="3">(0.130)</td>
                  <td data-row="8" data-col="4">(0.128)</td>
                  <td data-row="8" data-col="5">(0.104)</td>
                  <td data-row="8" data-col="6">(0.155)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">College</td>
                  <td data-row="9" data-col="2">0.269†</td>
                  <td data-row="9" data-col="3">0.174</td>
                  <td data-row="9" data-col="4">0.141</td>
                  <td data-row="9" data-col="5">0.315*</td>
                  <td data-row="9" data-col="6">0.281†</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.151)</td>
                  <td data-row="10" data-col="3">(0.161)</td>
                  <td data-row="10" data-col="4">(0.149)</td>
                  <td data-row="10" data-col="5">(0.158)</td>
                  <td data-row="10" data-col="6">(0.159)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">Trump x ConRep</td>
                  <td data-row="11" data-col="2">0.334</td>
                  <td data-row="11" data-col="3">0.343</td>
                  <td data-row="11" data-col="4">0.468*</td>
                  <td data-row="11" data-col="5">0.370†</td>
                  <td data-row="11" data-col="6">0.579*</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.219)</td>
                  <td data-row="12" data-col="3">(0.209)</td>
                  <td data-row="12" data-col="4">(0.212)</td>
                  <td data-row="12" data-col="5">(0.218)</td>
                  <td data-row="12" data-col="6">(0.249)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Climate x ConRep</td>
                  <td data-row="13" data-col="2">-0.419†</td>
                  <td data-row="13" data-col="3">-0.254</td>
                  <td data-row="13" data-col="4">-0.074</td>
                  <td data-row="13" data-col="5">-0.172</td>
                  <td data-row="13" data-col="6">0.282</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1"></td>
                  <td data-row="14" data-col="2">(0.221)</td>
                  <td data-row="14" data-col="3">(0.210)</td>
                  <td data-row="14" data-col="4">(0.209)</td>
                  <td data-row="14" data-col="5">(0.209)</td>
                  <td data-row="14" data-col="6">(0.238)</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">Trump x LibDem</td>
                  <td data-row="15" data-col="2">-0.056</td>
                  <td data-row="15" data-col="3">-0.090</td>
                  <td data-row="15" data-col="4">-0.091</td>
                  <td data-row="15" data-col="5">-0.128</td>
                  <td data-row="15" data-col="6">-0.107</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1"></td>
                  <td data-row="16" data-col="2">(0.165)</td>
                  <td data-row="16" data-col="3">(0.177)</td>
                  <td data-row="16" data-col="4">(0.181)</td>
                  <td data-row="16" data-col="5">(0.140)</td>
                  <td data-row="16" data-col="6">(0.218)</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">Climate x LibDem</td>
                  <td data-row="17" data-col="2">-0.222</td>
                  <td data-row="17" data-col="3">-0.216</td>
                  <td data-row="17" data-col="4">-0.120</td>
                  <td data-row="17" data-col="5">-0.144</td>
                  <td data-row="17" data-col="6">0.191</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1"></td>
                  <td data-row="18" data-col="2">(0.187)</td>
                  <td data-row="18" data-col="3">(0.190)</td>
                  <td data-row="18" data-col="4">(0.181)</td>
                  <td data-row="18" data-col="5">(0.155)</td>
                  <td data-row="18" data-col="6">(0.215)</td>
                </tr>
                <tr>
                  <td data-row="19" data-col="1">Trump x College</td>
                  <td data-row="19" data-col="2">-0.026</td>
                  <td data-row="19" data-col="3">-0.056</td>
                  <td data-row="19" data-col="4">0.019</td>
                  <td data-row="19" data-col="5">0.063</td>
                  <td data-row="19" data-col="6">0.174</td>
                </tr>
                <tr>
                  <td data-row="20" data-col="1"></td>
                  <td data-row="20" data-col="2">(0.215)</td>
                  <td data-row="20" data-col="3">(0.218)</td>
                  <td data-row="20" data-col="4">(0.222)</td>
                  <td data-row="20" data-col="5">(0.214)</td>
                  <td data-row="20" data-col="6">(0.231)</td>
                </tr>
                <tr>
                  <td data-row="21" data-col="1">College x ConRep</td>
                  <td data-row="21" data-col="2">-0.186</td>
                  <td data-row="21" data-col="3">-0.220</td>
                  <td data-row="21" data-col="4">-0.133</td>
                  <td data-row="21" data-col="5">-0.277</td>
                  <td data-row="21" data-col="6">-0.100</td>
                </tr>
                <tr>
                  <td data-row="22" data-col="1"></td>
                  <td data-row="22" data-col="2">(0.218)</td>
                  <td data-row="22" data-col="3">(0.213)</td>
                  <td data-row="22" data-col="4">(0.209)</td>
                  <td data-row="22" data-col="5">(0.233)</td>
                  <td data-row="22" data-col="6">(0.235)</td>
                </tr>
                <tr>
                  <td data-row="23" data-col="1">College x LibDem</td>
                  <td data-row="23" data-col="2">-0.263</td>
                  <td data-row="23" data-col="3">-0.227</td>
                  <td data-row="23" data-col="4">-0.234</td>
                  <td data-row="23" data-col="5">-0.408*</td>
                  <td data-row="23" data-col="6">-0.208</td>
                </tr>
                <tr>
                  <td data-row="24" data-col="1"></td>
                  <td data-row="24" data-col="2">(0.173)</td>
                  <td data-row="24" data-col="3">(0.186)</td>
                  <td data-row="24" data-col="4">(0.176)</td>
                  <td data-row="24" data-col="5">(0.173)</td>
                  <td data-row="24" data-col="6">(0.202)</td>
                </tr>
                <tr>
                  <td data-row="25" data-col="1">Trump x ConRep x College</td>
                  <td data-row="25" data-col="2">-0.459</td>
                  <td data-row="25" data-col="3">-0.082</td>
                  <td data-row="25" data-col="4">-0.220</td>
                  <td data-row="25" data-col="5">-0.465</td>
                  <td data-row="25" data-col="6">-0.262</td>
                </tr>
                <tr>
                  <td data-row="26" data-col="1"></td>
                  <td data-row="26" data-col="2">(0.318)</td>
                  <td data-row="26" data-col="3">(0.299)</td>
                  <td data-row="26" data-col="4">(0.312)</td>
                  <td data-row="26" data-col="5">(0.335)</td>
                  <td data-row="26" data-col="6">(0.334)</td>
                </tr>
                <tr>
                  <td data-row="27" data-col="1">Trump x LibDem x College</td>
                  <td data-row="27" data-col="2">-0.027</td>
                  <td data-row="27" data-col="3">0.025</td>
                  <td data-row="27" data-col="4">-0.042</td>
                  <td data-row="27" data-col="5">0.024</td>
                  <td data-row="27" data-col="6">-0.094</td>
                </tr>
                <tr>
                  <td data-row="28" data-col="1"></td>
                  <td data-row="28" data-col="2">(0.241)</td>
                  <td data-row="28" data-col="3">(0.251)</td>
                  <td data-row="28" data-col="4">(0.254)</td>
                  <td data-row="28" data-col="5">(0.233)</td>
                  <td data-row="28" data-col="6">(0.287)</td>
                </tr>
                <tr>
                  <td data-row="29" data-col="1">Intercept</td>
                  <td data-row="29" data-col="2">1.951***</td>
                  <td data-row="29" data-col="3">2.310***</td>
                  <td data-row="29" data-col="4">2.232***</td>
                  <td data-row="29" data-col="5">1.744***</td>
                  <td data-row="29" data-col="6">2.923***</td>
                </tr>
                <tr>
                  <td data-row="30" data-col="1"></td>
                  <td data-row="30" data-col="2">(0.104)</td>
                  <td data-row="30" data-col="3">(0.110)</td>
                  <td data-row="30" data-col="4">(0.105)</td>
                  <td data-row="30" data-col="5">(0.086)</td>
                  <td data-row="30" data-col="6">(0.123)</td>
                </tr>
                <tr>
                  <td data-row="31" data-col="1">Climate x College</td>
                  <td data-row="31" data-col="2">-0.191</td>
                  <td data-row="31" data-col="3">-0.186</td>
                  <td data-row="31" data-col="4">-0.212</td>
                  <td data-row="31" data-col="5">-0.074</td>
                  <td data-row="31" data-col="6">0.072</td>
                </tr>
                <tr>
                  <td data-row="32" data-col="1"></td>
                  <td data-row="32" data-col="2">(0.228)</td>
                  <td data-row="32" data-col="3">(0.224)</td>
                  <td data-row="32" data-col="4">(0.217)</td>
                  <td data-row="32" data-col="5">(0.225)</td>
                  <td data-row="32" data-col="6">(0.229)</td>
                </tr>
                <tr>
                  <td data-row="33" data-col="1">Climate x ConRep x College</td>
                  <td data-row="33" data-col="2">-0.075</td>
                  <td data-row="33" data-col="3">0.040</td>
                  <td data-row="33" data-col="4">-0.058</td>
                  <td data-row="33" data-col="5">-0.123</td>
                  <td data-row="33" data-col="6">-0.418</td>
                </tr>
                <tr>
                  <td data-row="34" data-col="1"></td>
                  <td data-row="34" data-col="2">(0.324)</td>
                  <td data-row="34" data-col="3">(0.298)</td>
                  <td data-row="34" data-col="4">(0.303)</td>
                  <td data-row="34" data-col="5">(0.334)</td>
                  <td data-row="34" data-col="6">(0.330)</td>
                </tr>
                <tr>
                  <td data-row="35" data-col="1">Climate x LibDem x College</td>
                  <td data-row="35" data-col="2">-0.010</td>
                  <td data-row="35" data-col="3">0.144</td>
                  <td data-row="35" data-col="4">0.140</td>
                  <td data-row="35" data-col="5">0.004</td>
                  <td data-row="35" data-col="6">-0.241</td>
                </tr>
                <tr>
                  <td data-row="36" data-col="1"></td>
                  <td data-row="36" data-col="2">(0.261)</td>
                  <td data-row="36" data-col="3">(0.263)</td>
                  <td data-row="36" data-col="4">(0.253)</td>
                  <td data-row="36" data-col="5">(0.248)</td>
                  <td data-row="36" data-col="6">(0.286)</td>
                </tr>
                <tr>
                  <td data-row="37" data-col="1">Num.Obs.</td>
                  <td data-row="37" data-col="2">3113</td>
                  <td data-row="37" data-col="3">3113</td>
                  <td data-row="37" data-col="4">3113</td>
                  <td data-row="37" data-col="5">3113</td>
                  <td data-row="37" data-col="6">3113</td>
                </tr>
                <tr>
                  <td data-row="38" data-col="1">R2</td>
                  <td data-row="38" data-col="2">0.331</td>
                  <td data-row="38" data-col="3">0.368</td>
                  <td data-row="38" data-col="4">0.359</td>
                  <td data-row="38" data-col="5">0.314</td>
                  <td data-row="38" data-col="6">0.165</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</figure>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1 unnumbered">


</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-abramowitzUnitedStatesRacial2019" class="csl-entry" role="listitem">
Abramowitz, Alan I., and Jennifer McCoy. 2019. <span>“United <span>States</span>: <span>Racial Resentment</span>, <span>Negative Partisanship</span>, and <span>Polarization</span> in <span class="nocase">Trump’s America</span>.”</span> <em>The ANNALS of the American Academy of Political and Social Science</em> 681(1): 137–56.
</div>
<div id="ref-bakkerUnderstandingPartisanCue2019" class="csl-entry" role="listitem">
Bakker, Bert, Yphtach Lelkes, and Ariel Malka. 2019. <span>“Understanding <span>Partisan Cue Receptivity</span>: <span>Tests</span> of <span>Predictions</span> from the <span>Bounded Rationality</span> and <span>Expressive Utility Perspectives</span>.”</span> <em>The Journal of Politics</em>.
</div>
<div id="ref-bergquistEnergyPolicyPublic2020" class="csl-entry" role="listitem">
Bergquist, Parrish, David M Konisky, and John Kotcher. 2020. <span>“Energy <span>Policy</span> and <span>Public Opinion</span>: <span>Patterns</span>, <span>Trends</span> and <span>Future Directions</span>.”</span> <em>Progress in Energy</em> 2(3): 032003.
</div>
<div id="ref-carnesWhiteWorkingClass2020" class="csl-entry" role="listitem">
Carnes, Nicholas, and Noam Lupu. 2020. <span>“The <span>White Working Class</span> and the 2016 <span>Election</span>.”</span> <em>Perspectives on Politics</em> 18(1): 55–72.
</div>
<div id="ref-cprTrumpAdministrationOrders2025" class="csl-entry" role="listitem">
Colorado Public Radio. 2025. <span>“Trump Administration Orders Aging <span>Colorado</span> Coal Plant to Stay Open, One Day Before Closing.”</span> https://www.cpr.org/2025/12/31/trump-order-craig-power-plant-open/ (August 25, 2026).
</div>
<div id="ref-columbiaTrumpDeclaresNational2025" class="csl-entry" role="listitem">
Columbia Climate School, Sabin Center for Climate Change Law. 2025. <span>“President <span>Trump Declares National Energy Emergency</span>.”</span> https://climate.law.columbia.edu/content/president-trump-declares-national-energy-emergency (August 25, 2026).
</div>
<div id="ref-druckmanHowElitePartisan2013" class="csl-entry" role="listitem">
Druckman, James N., Erik Peterson, and Rune Slothuus. 2013. <span>“How <span>Elite Partisan Polarization Affects Public Opinion Formation</span>.”</span> <em>American Political Science Review</em> 107(01): 57–79.
</div>
<div id="ref-feldmanClimateChangePolarizing2018" class="csl-entry" role="listitem">
Feldman, Lauren, and P. Sol Hart. 2018. <span>“Climate <span>Change</span> as a <span>Polarizing Cue</span>: <span>Framing Effects</span> on <span>Public Support</span> for <span>Low-Carbon Energy Policies</span>.”</span> <em>Global Environmental Change</em> 51: 54–66.
</div>
<div id="ref-gustafsonRepublicansDemocratsDiffer2020" class="csl-entry" role="listitem">
Gustafson, Abel, Matthew H. Goldberg, John E. Kotcher, Seth A. Rosenthal, Edward W. Maibach, Matthew T. Ballew, and Anthony Leiserowitz. 2020. <span>“Republicans and <span>Democrats Differ</span> in <span>Why They Support Renewable Energy</span>.”</span> <em>Energy Policy</em> 141: 111448.
</div>
<div id="ref-hamiltonEducationPoliticsOpinions2011" class="csl-entry" role="listitem">
Hamilton, Lawrence C. 2011. <span>“Education, <span>Politics</span> and <span>Opinions</span> about <span>Climate Change Evidence</span> for <span>Interaction Effects</span>.”</span> <em>Climatic Change</em> 104(2): 231–42.
</div>
<div id="ref-kahanIdeologyMotivatedReasoning2013" class="csl-entry" role="listitem">
Kahan, Dan M. 2013. <span>“Ideology, <span>Motivated Reasoning</span>, and <span>Cognitive Reﬂection</span>.”</span> <em>Judgement and Decision Making</em> 8(4): 407–24.
</div>
<div id="ref-kamWhoToesParty2005" class="csl-entry" role="listitem">
Kam, Cindy. 2005. <span>“Who <span>Toes</span> the <span>Party Line</span>? <span>Cues</span>, <span>Values</span>, and <span>Individual Differences</span>.”</span> <em>Political Behavior</em> 27(2): 163–82.
</div>
<div id="ref-kitscheltSecularPartisanRealignment2019" class="csl-entry" role="listitem">
Kitschelt, Herbert, and Philipp Rehm. 2019. <span>“Secular <span>Partisan Realignment</span> in the <span>United States</span>: <span>The Socioeconomic Reconfiguration</span> of <span>White Partisan Support</span> Since the <span>New Deal Era</span>.”</span> <em>Politics &amp; Society</em> 47(3): 425–79.
</div>
<div id="ref-leeperPoliticalPartiesMotivated2014" class="csl-entry" role="listitem">
Leeper, Thomas J., and Rune Slothuus. 2014. <span>“Political <span>Parties</span>, <span>Motivated Reasoning</span>, and <span>Public Opinion Formation</span>.”</span> <em>Political Psychology</em> 35(S1): 129–56.
</div>
<div id="ref-mayerPartisanshipPoliticsEnergy2019" class="csl-entry" role="listitem">
Mayer, Adam. 2019. <span>“Partisanship, <span>Politics</span>, and the <span>Energy Transition</span> in the <span>United States</span>: <span>A Critical Review</span> and <span>Conceptual Framework</span>.”</span> <em>Energy Research &amp; Social Science</em> 53: 85–88.
</div>
<div id="ref-mcconnellGreenNewDeal2022" class="csl-entry" role="listitem">
McConnell, Kathryn. 2022. <span>“<span>‘<span>The Green New Deal</span>’</span> as <span>Partisan Cue</span>: <span>Evidence</span> from a <span>Survey Experiment</span> in the <span>Rural U</span>.<span>S</span>.”</span> <em>Environmental Politics</em> 0(0): 1–33.
</div>
<div id="ref-merkleyPartyCuesNews2021" class="csl-entry" role="listitem">
Merkley, Eric, and Dominik A. Stecula. 2021. <span>“Party <span>Cues</span> in the <span>News</span>: <span>Democratic Elites</span>, <span>Republican Backlash</span>, and the <span>Dynamics</span> of <span>Climate Skepticism</span>.”</span> <em>British Journal of Political Science</em> 51(4): 1439–56.
</div>
<div id="ref-merolaNumeracyPersuasiveEffect2016" class="csl-entry" role="listitem">
Mérola, Vittorio, and Matthew P. Hitt. 2016. <span>“Numeracy and the <span>Persuasive Effect</span> of <span>Policy Information</span> and <span>Party Cues</span>.”</span> <em>Public Opinion Quarterly</em> 80(2): 554–62.
</div>
<div id="ref-morganTrumpVotersWhite2018" class="csl-entry" role="listitem">
Morgan, Stephen L., and Jiwon Lee. 2018. <span>“Trump <span>Voters</span> and the <span>White Working Class</span>.”</span> <em>Sociological Science</em> 5: 234–45.
</div>
<div id="ref-nprTrumpAdministrationPauses2025" class="csl-entry" role="listitem">
NPR. 2025. <span>“Trump Administration Pauses Offshore Wind Projects Along the <span>East Coast</span>.”</span> https://www.npr.org/2025/12/23/nx-s1-5652025/trump-administration-pauses-offshore-wind-projects-along-the-east-coast (August 25, 2026).
</div>
<div id="ref-petersenMotivatedReasoningPolitical2013" class="csl-entry" role="listitem">
Petersen, Michael Bang, Martin Skov, Søren Serritzlew, and Thomas Ramsøy. 2013. <span>“Motivated <span>Reasoning</span> and <span>Political Parties</span>: <span>Evidence</span> for <span>Increased Processing</span> in the <span>Face</span> of <span>Party Cues</span>.”</span> <em>Political Behavior</em> 35(4): 831–54.
</div>
<div id="ref-sancesHowUnusualWas2019" class="csl-entry" role="listitem">
Sances, Michael W. 2019. <span>“How <span>Unusual Was</span> 2016? <span>Flipping Counties</span>, <span>Flipping Voters</span>, and the <span>Education</span> Since 1952.”</span> <em>Perspectives on Politics</em> 17(3): 666–78.
</div>
<div id="ref-schaffnerPartisanHeuristicLowInformation2002" class="csl-entry" role="listitem">
Schaffner, Brian F., and Matthew J. Streb. 2002. <span>“The <span>Partisan Heuristic</span> in <span>Low-Information Elections</span>.”</span> <em>Public Opinion Quarterly</em> 66(4): 559–81.
</div>
<div id="ref-slothuusPoliticalPartiesMotivated2010" class="csl-entry" role="listitem">
Slothuus, Rune, and Claes de Vreese. 2010. <span>“Political <span>Parties</span>, <span>Motivated Reasoning</span>, and <span>Issue Framing Effects</span>.”</span> <em>The Journal of Politics</em> 72(3): 630–45.
</div>
<div id="ref-taberMotivatedSkepticismEvaluation2006" class="csl-entry" role="listitem">
Taber, Charles S., and Milton Lodge. 2006. <span>“Motivated <span>Skepticism</span> in the <span>Evaluation</span> of <span>Political Beliefs</span>.”</span> <em>American Journal of Political Science</em> 50(3): 755–69.
</div>
<div id="ref-tappinEstimatingCausalEffects2026" class="csl-entry" role="listitem">
Tappin, Ben M., and Ryan McKay. 2026. <span>“Estimating the <span>Causal Effects</span> of <span>Cognitive Effort</span> and <span>Policy Information</span> on <span>Party Cue Influence</span>.”</span> <em>Political Psychology</em> 47(2).
</div>
<div id="ref-postTrumpAdministrationSlashes2025" class="csl-entry" role="listitem">
The Washington Post. 2025. <span>“Trump Administration Slashes Tax Credits for Solar, Wind Projects.”</span> https://www.washingtonpost.com/climate-environment/2025/08/15/tax-credits-renewable-energy-projects/ (August 25, 2026).
</div>
<div id="ref-doeKeyTakeawaysPresidents2025" class="csl-entry" role="listitem">
U.S. Department of Energy, Office of Nuclear Energy. 2025. <span>“9 <span>Key Takeaways</span> from <span>President Trump</span>’s <span>Executive Orders</span> on <span>Nuclear Energy</span>.”</span> https://www.energy.gov/ne/articles/9-key-takeaways-president-trumps-executive-orders-nuclear-energy (August 25, 2026).
</div>
<div id="ref-doiInteriorUnleashesAmerican2025" class="csl-entry" role="listitem">
U.S. Department of the Interior. 2025. <span>“Interior <span>Unleashes American Coal Power</span> in <span>Bold Move</span> to <span>Advance Trump Administration Priorities</span>.”</span> https://www.doi.gov/pressreleases/interior-unleashes-american-coal-power-bold-move-advance-trump-administration (August 25, 2026).
</div>
<div id="ref-zingherDiplomaDivideEducational2022" class="csl-entry" role="listitem">
Zingher, Joshua N. 2022. <span>“<span>TRENDS</span>: <span>Diploma</span> Divide: <span>Educational</span> Attainment and the Realignment of the <span>American</span> Electorate.”</span> <em>Political Research Quarterly</em> 76: 263–77.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The table of results in shown in the Appendix.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>I also examined the interaction of education and the climate cue. Like the Trump cue, there were no significant difference. The results are shown in the Appendix.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>