{
  "hash": "cb6ce0920a4fd8fa30e28cf7935169c9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Partisan vs Climate Cues and Public Opinion about Trump's Actions on Energy\"\nbibliography: references.bib\ncsl: american-political-science-association.csl\nfig-cap-location: top\nfontfamily: ebgaramond\nlink-bibliography: false\nformat:\n  html:\n    author:\n      - name: Matthew C. Nowlin\n        email: matthew.nowlin@uta.edu\n        corresponding: true\n        affiliations:\n          - name: University of Texas at Arlington\n            department: Department of Political Science\n  pdf:\n    author:\n      - name: \"Matthew C. Nowlin^[Associate Professor, Department of Political Science, University of Texas at Arlington. Email: matthew.nowlin@uta.edu]\"\n    include-in-header:\n      text: |\n        \\usepackage{setspace}\n        \\usepackage{dcolumn}\n        \\usepackage{float}\n        \\usepackage{amsmath}\n        \\addtokomafont{disposition}{\\rmfamily}\n        \\normalem\n  docx:\n    author:\n      - name: \"Matthew C. Nowlin^[Associate Professor, Department of Political Science, University of Texas at Arlington. Email: matthew.nowlin@uta.edu]\"\n    reference-doc: custom-reference-doc.docx\n---\n\n\n\n**Abstract**: The second Trump administration has made strong and concerted efforts to shape energy production in the United States. In particular, the administration has moved to strengthen the fossil fuel industry and limit the use of renewable energy sources. Increasing the use of renewable sources is needed to address climate change. Yet, even with the connection to climate change, public support for renewable energy and policies supporting the development of renewable energy sources is not as polarized as support for climate change policies. However, the efforts of the Trump administration may serve to polarize public opinion on energy sources and the government's role in shaping their availability. In this paper, I develop a pre-registered survey experiment to examine the polarization in support for several recent administration actions on energy when respondents are given a Trump cue, a climate change cue, and no cues. Specifically, I will survey 3,000 respondents recruited from Cloud Research, with 1,000 participants receiving a Trump cue, 1,000 participants receiving a climate cue, and 1,000 respondents in the control condition, who will receive no cue. Respondents in each condition will be asked about their level of support for several actions, including limiting tax credits for wind and solar projects, requiring coal plants to remain open, opening federal lands for coal leasing, cancelling a nearly complete offshore wind project, and shortening the timeline of regulatory approval for new nuclear plants. I compare the impacts of the Trump cue and climate cue on support for Trump administration actions across partisanship, ideology, and education level.   \n\n*Paper prepared for submission to the Annual Meeting of the American Political Science Association, September 2026* \n\n# Introduction \n\nSince returning to office for the second time, President Trump has sought to provide support for fossil fuels while sidelining renewable sources of energy. He has also downplayed the threat of climate change and through executive actions has worked to limit approaches to address climate change. Climate change is a highly polarized issue among the US public. Historically, energy has not been polarized as the public views on energy tend to have been focused on affordability [@ansolabehereCheapCleanHow2016]. Yet, in recent years energy sources have been more polarized with Republican's tending to favor fossil fuel sources, and Democrats favoring renewable sources. This increasing polarization may be a result of the connection between renewable energy and climate change. Additionally, Trump's actions may serve to further polarize the public on energy issues. \n\nPrevious research has noted the importance of cues in shaping public opinion. Cues often provide a shortcut which allows the mass public, who are likely ignorant of the details of politics and policy issues, to infer reasonably consistent views on a host of issues. Partisan cues in particular are known to be important sources of information for the public [@kamWhoToesParty2005; @schaffnerPartisanHeuristicLowInformation2002]. Additionally, the impact of cues may vary by level of education and political sophistication, with those less knowledgeable relying more heavily on cues than those with more knowledge [@kamWhoToesParty2005; @merolaNumeracyPersuasiveEffect2016]. With Trump's support among those without a college education, it is likely that a Trump cue will be particularly influential on that group [@morganTrumpVotersWhite2018; @zingherTRENDSDiplomaDivide2022].   \n\nIn this paper, I examine the role that partisan and climate cues have on support for several of Trump's actions on energy in the first year of his second term. The actions I examine include limiting tax credits for wind and solar projects, requiring coal plants to remain open, opening federal lands for coal leasing, cancelling a nearly complete offshore wind project, and shortening the timeline of regulatory approval for new nuclear plants. Specifically, I use a survey experiment where respondents were randomly assigned to receive a Trump cue, a statement that the actions came from the Trump Administration versus the federal government, a climate cue, a statement about climate scientists being concerned that some of the actions could make climate change worse, or a control condition with no cue. I test several preregistered hypotheses regarding how respondents will respond to the Trump and climate cues based on political beliefs and education compared to those in the control group.  \n\nOverall, I find that the Trump cue, but not the climate cue, increased support for Trump's energy actions among conservative Republicans, significantly so for opening federal lands to coal leasing and for shortening nuclear licensing timelines. The climate cue had little effect on Republicans, except for a decrease in support for eliminating tax credits for wind and solar projects, the one action that most directly curtails renewable energy. Liberal Democrats were largely unresponsive to either cue, and neither cue's effects were conditioned by whether respondents held a college degree. These results suggest that Trump's actions on energy are more likely to polarize public opinion through their association with Trump himself than through their connection to climate change.\n\n# Polarization on Energy Issues\n\nPublic views on energy in the US has grown increasingly polarized along partisan lines, even as aggregate support for many energy sources and policies has remained relatively stable. Using data from three long-running national surveys spanning nearly two decades, Bergquist, Konisky, and Kotcher [-@bergquistEnergyPolicyPublic2020] find that partisanship is the strongest predictor of energy policy preferences, with Republicans positioned nearly a full standard deviation from Democrats on a composite measure of support for shifting from fossil fuels to renewable sources of energy. This partisan gap has widened since 2008, even as support for expanding fossil fuel extraction has declined among the public overall. Bergquist et al. [-@bergquistEnergyPolicyPublic2020] also show that when the costs of clean energy policies are made explicit, support declines by a similar magnitude for both Democrats and Republicans, suggesting that the partisan divide in energy opinion is not simply a function of differential cost sensitivity.\n\nYet this partisan divide is not the same across every energy source [@ansolabehereCheapCleanHow2016; @bergquistEnergyPolicyPublic2020]. Fossil fuels carry the deepest partisan split of any source relevant to this study. Democrats and liberals are considerably cooler toward coal than Republicans and conservatives [@hartPoliticalPolarizationSupport2021], and they voice more unease about the extraction methods behind oil and gas development [@davisEnergyAbundanceEnvironmental2014; @raimiPartisanshipProximityPredict2020]. Underlying this gap is a difference in what each side weighs most heavily: Democrats and liberals point to the health, environmental, and climate harms of fossil fuels, while Republicans and conservatives point to the jobs, prices, and energy security they provide [@clarkePoliticsScientificConsensus2019; @howellSeeingRiskColoredGlasses2019]. Wind and solar sit at the other end of the spectrum. Majorities across the partisan divide have favored expanding these sources, and where partisans disagree, it is a matter of how much to expand renewables rather than whether to do so at all [@bergquistEnergyPolicyPublic2020; @hamiltonChangeWindUS2018; @hawesClimateSciencePolitics2022]. Nuclear power falls in between, drawing modestly more support from the right than the left, but without the sharp partisan split seen for fossil fuels [@yeoPartisanAmplificationRisk2014; @mcbethPoliticalIdeologyNuclear2023a].\n\nUnderlying this partisan divide are different reasons for supporting, or opposing, a transition toward renewable energy. As noted by Gustafson et al. [-@gustafsonRepublicansDemocratsDiffer2020], Republicans' support for renewable energy is driven more by considerations of economic costs and benefits, whereas Democrats' support is driven more by concern about global warming. Using a nationally representative survey of registered voters, they found that Democrats most often cite \"reduce global warming\" as their single most important reason to support renewable energy (chosen by 33 percent of Democrats, compared to 7 percent of Republicans), while Republicans more often cite reasons tied to energy costs and energy independence. This divergence in underlying motivation is likely important for understanding how partisan and climate cues will separately shape support for energy actions: a cue that foregrounds cost or energy security is likely to resonate differently with Republicans than a cue that foregrounds climate change, and vice versa for Democrats.\n\nMayer [-@mayerPartisanshipPoliticsEnergy2019] argues that this partisan divide in energy attitudes reflects several distinct dimensions of partisanship rather than a single underlying mechanism. Specifically, Mayer [-@mayerPartisanshipPoliticsEnergy2019] proposes a four-part conceptual framework encompassing cue receptivity, expressive partisanship, negative partisanship, and performative partisanship, each of which may separately shape how citizens respond to information about energy and the energy transition. This framework is useful for anticipating how the cues examined in the current study, a Trump cue and a climate change cue, are likely to operate through different channels: a Trump cue is likely to activate expressive and cue-receptive partisanship among Republicans, while a climate cue is likely to activate the substantive climate concern already documented among Democrats.\n\nThis unevenness in baseline polarization matters for interpreting the actions examined here. Two of the actions, keeping coal plants open and opening federal land to coal leasing, fall on the fossil fuel side of the divide, where partisan reactions to a Trump or climate cue should be sharpest. Two others, limiting wind and solar tax credits and cancelling the offshore wind project, intervene in a policy area where the public, Republicans included, has tended to be supportive [@bergquistEnergyPolicyPublic2020; @hamiltonChangeWindUS2018], so cue effects there may be more muted. The fifth action, accelerating nuclear licensing, touches a source with the least partisan baggage of the five [@yeoPartisanAmplificationRisk2014; @mcbethPoliticalIdeologyNuclear2023a], offering a useful contrast case in which a Trump or climate cue has the least polarized ground to work with.\n\nIn the next section, I discuss the theoretical mechanisms of partisan cue-taking in greater detail and describe how Trump and climate cues are likely to differentially shape support for Trump's actions on energy.\n\n# Cues and Cue-Taking\n\nPartisan cues function as a heuristic that allows citizens to form opinions on complex policy issues without extensive information [@kamWhoToesParty2005; @schaffnerPartisanHeuristicLowInformation2002]. Rather than evaluating the substantive merits of a policy, citizens often infer their own position from the position taken by their preferred party or its elites, a process that is well documented across a wide range of issues [@slothuusPoliticalPartiesMotivated2010; @leeperPoliticalPartiesMotivated2014]. This cue-taking is best understood through the lens of motivated reasoning, wherein citizens process information in a way that protects and reinforces their prior partisan commitments rather than arriving at accuracy [@taberMotivatedSkepticismEvaluation2006; @petersenMotivatedReasoningPolitical2013]. As elite polarization has intensified, party cues have become an increasingly powerful, and at times dominant, force in opinion formation, often overwhelming the effect of substantive policy information [@druckmanHowElitePartisan2013].\n\nClimate change and energy policy are particularly susceptible to this dynamic. As shown by Feldman and Hart [-@feldmanClimateChangePolarizing2018], simply attaching a climate change frame or a cue from a Democratic source to an energy policy is often enough to depress support among Republicans, even when the underlying policy is left unchanged. Similarly, out-group cues from Democratic elites have been found to produce a durable backlash in climate skepticism among Republican identifiers [@merkleyPartyCuesNews2021], and partisan cue-taking extends to more recent and salient energy proposals, such as the Green New Deal [@mcconnellGreenNewDeal2022]. These findings suggest that Trump cues and climate cues are likely to activate similar, but oppositely signed, partisan reactions to actions on energy: conservative Republicans are likely to become more supportive when an action is cued as coming from Trump or as countering climate change, whereas liberal Democrats are likely to become less supportive under the same cues.\n\nA cue naming Trump specifically is theoretically distinct from a generic partisan or \"federal government\" cue. Individual elites, rather than parties in the abstract, tend to carry more weight in shaping public opinion [@nicholsonPolarizingCues2012], and elite cues more broadly rank among the strongest known predictors of public views on climate change [@brulleShiftingPublicOpinion2012]. Trump in particular has repeatedly proven capable of moving opinion on issues far outside energy: attitudes toward him have been shown to shift public views on immigration [@taylorTrumpEffectImmigration2026] and trade policy [@essigTrumpEffectPolitical2021], and presidents more generally appear able to sharpen partisan divides on climate policy simply by becoming associated with it [@childreePolarizingFiguresPolarized2026]. Given that his administration has taken concrete steps to expand fossil fuel production while curbing renewable energy development [@gerrardTrumpsMultiProngedAttack2025; @joselowHowTrumpsFirst2025], there is good reason to expect this same dynamic to carry over into energy attitudes specifically.\n\nWhether cue-taking of this kind is more pronounced among the less educated, however, is not as settled as the classic heuristics literature might suggest. Early accounts of the partisan heuristic emphasize that cue-taking substitutes for the cognitive effort required to process substantive information, implying that citizens with fewer cognitive resources, such as those without a college degree, should rely on party cues the most [@kamWhoToesParty2005]. Numeracy research supports this account: low-numeracy respondents rely more heavily on party cues, while high-numeracy respondents are more likely to update toward substantive policy information when it is available [@merolaNumeracyPersuasiveEffect2016]. Yet effortful thinking alone does not appear to be sufficient to reduce cue reliance; it is the availability of policy information, not cognitive effort per se, that weakens party cue effects [@tappinEstimatingCausalEffects2026]. Complicating the picture further, political sophistication and education are also associated with more effective motivated reasoning, meaning that better-informed citizens may process cue-congruent information more efficiently rather than less [@kahanIdeologyMotivatedReasoning2013]. Bakker, Lelkes, and Malka [-@bakkerUnderstandingPartisanCue2019] similarly find that cue receptivity is not simply a function of bounded rationality but is strongest when cognitive resources are placed in service of expressive, identity-affirming reasoning. Consistent with this more conditional pattern, education has been found to amplify, rather than dampen, partisan polarization over climate change, particularly among conservatives [@hamiltonEducationPoliticsOpinions2011]. Together, this literature suggests that a college degree is likely to shape responsiveness to Trump and climate cues, but the direction of that relationship is less straightforward than the low-information heuristic model implies.\n\nAdditionally, a Trump cue may act differently than a typical partisan cue because of Trump's purported strength among \"working-class\" voters, particularly white working class voters.\n\nThis pattern is consistent with a broader realignment of the American electorate along educational lines. Kitschelt and Rehm [-@kitscheltSecularPartisanRealignment2019] show that education, particularly when combined with income, has become one of the strongest predictors of white partisan support since the New Deal era, with non-college whites increasingly aligned with the Republican party. Zingher [-@zingherTRENDSDiplomaDivide2022] similarly documents a widening \"diploma divide,\" finding that educational attainment has become an increasingly strong predictor of both partisanship and vote choice since 2000, with less-educated counties trending Republican and more-educated counties trending Democratic. This divide reached a high point in the 2016 election: Sances [-@sancesHowUnusualWas2019] finds that the education-party correlation was the strongest on record that year, and Morgan and Lee [-@morganTrumpVotersWhite2018] show that white working-class voters, including many who had supported Obama in 2012, were disproportionately likely to switch to Trump. Abramowitz and McCoy [-@abramowitzUnitedStatesRacial2019] argue that this appeal was rooted in racial resentment, attracting strong support from white working-class voters while repelling many college-educated whites.\n\nHowever, the centrality of the white working class to Trump's coalition is not without dispute. Carnes and Lupu [-@carnesWhiteWorkingClass2021] examine the available survey evidence and find that several common claims about the white working class in 2016, including the claim that this group was pivotal to Trump's victory, are not well supported once turnout and longer-term partisan trends are taken into account. This unresolved debate is likely important for interpreting how a Trump cue operates: if support for Trump is substantially class-inflected rather than a straightforward partisan signal, a Trump cue may activate identity-based responses among non-college conservative Republicans and liberal Democrats that a generic partisan or climate cue would not. Whether this class-based moderation is actually present, however, is an empirical question that has not, to my knowledge, been tested directly in the context of cue-taking on energy policy.\n\n## Hypotheses\n\nTaken together, this literature points to two channels through which the Trump and climate cues could shape support for Trump's actions on energy. The first is a straightforward partisan cue-taking channel: because a Trump cue is likely to activate expressive and cue-receptive partisanship among Republicans while signaling an out-group threat to Democrats, and a climate cue is likely to tap the substantive climate concern that already distinguishes Democrats from Republicans, conservative Republicans and liberal Democrats should respond most strongly to both cues, and in opposite directions. The second is a possible education channel tied to the debate over how class-inflected Trump's support actually is: if a Trump cue draws on identity-based appeal among non-college conservatives rather than functioning as an ordinary partisan signal, its effects should be concentrated among respondents without a college degree. I test both channels with the following hypotheses.\n\n> H1: Conservative Republicans who receive the Trump or climate change cue will be more supportive of Trump's actions on energy than others \n\n> H2: Liberal Democrats who receive the Trump or climate change cue will be less supportive of Trump's actions on energy than others \n\n> H3: Conservative Republicans without a college degree who receive the Trump cue will be more supportive of Trump's actions on energy than others\n\n> H4: Liberal Democrats without a college degree who receive the Trump cue will be less supportive of Trump's actions on energy than others \n\n\n# Data and Measures \n\nThe data for were obtained from a survey of a quota-based sample of US residents recruited through Cloud Research. The quota-based sampling approach using US Census data to help ensure representation across key demographic groups, including age, gender, and race. The survey was internet-based and administered using QuestionPro and was fielded from April 10 to April 15, 2026. Survey weights were applied to ensure that the sample was representative of the US population. \n\nEarly in his second term, Trump declared a national energy emergency, directing federal agencies to use emergency statutory authorities to speed the development and authorization of energy projects and rescinding a number of prior climate-related executive orders [@houseDeclaringNationalEnergy2025]. In the year that followed, the administration acted on several fronts to advance this agenda. The Department of the Treasury tightened the rules that wind and solar developers rely on to qualify for federal tax credits [@springTrumpAdministrationLimits2025], while the Department of Energy repeatedly invoked emergency authority to keep aging coal plants running past their planned retirement dates, including plants in Michigan, Washington, Indiana, and Colorado [@thakoreTrumpAdministrationOrders2025]. The Department of the Interior opened 13.1 million acres of federal land in Montana, North Dakota, and Wyoming for coal leasing [@InteriorUnleashesAmerican2025], and separately halted construction on offshore wind projects along the East Coast, two of which were nearly complete [@wasserTrumpAdministrationPauses2025]. At the same time, the administration sought to accelerate nuclear energy development, directing the Nuclear Regulatory Commission to shorten its licensing review to under 18 months for new reactors [@usdepartmentofenergy9KeyTakeaways2025; @TrumpsLicensingGoals2025].\n\n\nTo measure the impact of the cues on support for Trump Administration actions on energy, respondents were randomly assigned to one of three conditions, including a Trump cue, a climate cue, and control condition with no cue. Overall, the groups were roughly equal, with the Trump cue, *n* = 1049, the climate cue, *n* = 1013, and the control, *n* = 1051, from the sample of *N* = 3113. The Trump cue identified the actions as being done by the _Trump Administration_, whereas the climate cue and the control conditions indicated the actions were by the _federal government_. The climate cue included a statement about concerns that climate scientists have about the impact of the actions on climate change. The question wording was as follows: \n\n> Recently, the [_Trump Administration_/_Federal government_] took several actions to shape electricity generation in the U.S.\n\n> **Climate cue**: _Scientists are concerned that the actions associated with coal, wind, and solar energy will make climate change worse._\n\n> Using a scale of 1 to 5, where 1 means strongly oppose and 5 means strongly support, how do you feel about the following actions of the [_Trump Administration_/_Federal government_]? [The following were randomized]\n\n> * The [_Trump Administration_/_Federal government_] limiting the eligibility of wind and solar energy projects for federal tax credits\n> * The [_Trump Administration_/_Federal government_] requiring coal plants that were set to retire to remain open\n> * The [_Trump Administration_/_Federal government_] opening 13.1 million acres of federal land for coal leasing\n> * The [_Trump Administration_/_Federal government_] cancelling an offshore wind project that was nearly complete\n> * The [_Trump Administration_/_Federal government_] shortening the time it takes to approve and license the construction of new nuclear power plants\n\nThe main independent variables of interest are political beliefs, including conservative Republicans and liberal Democrats, with other political belief (moderate independents, conservative Democrats, liberal Republicans) as the excluded referent. College is dummy variable, 1 = completed a college degree, 0 = did not. @tbl-descriptives shows the descriptive statistics for each of the variables. \n\n\n::: {#tbl-descriptives .cell tbl-cap='Descriptive Statistics for Dependent and Independent Variables'}\n::: {.cell-output-display}\n\n+------------------+-------+------+------+\n| Variable         | Range | Mean | SD   |\n+==================+=======+======+======+\n| Tax Credits      | 1-5   | 2.26 | 1.28 |\n+------------------+-------+------+------+\n| Coal Open        | 1-5   | 2.48 | 1.25 |\n+------------------+-------+------+------+\n| Coal Leasing     | 1-5   | 2.39 | 1.28 |\n+------------------+-------+------+------+\n| Cancel Wind      | 1-5   | 2.09 | 1.25 |\n+------------------+-------+------+------+\n| Nuclear          | 1-5   | 2.97 | 1.33 |\n+------------------+-------+------+------+\n| Cons. Republican | 0-1   | 0.40 | 0.49 |\n+------------------+-------+------+------+\n| Lib. Democrat    | 0-1   | 0.37 | 0.48 |\n+------------------+-------+------+------+\n| College          | 0-1   | 0.36 | 0.48 |\n+------------------+-------+------+------+\n:::\n:::\n\n\nIn terms of support for the various actions, they each seem to hover around the mid-point of the 1 to 5 scale with cancelling nearly complete wind projects showing the least support at 2.09 and reducing nuclear energy regulations showing the most at 2.97.\n\n# Results\n\nThe first two hypotheses posited that political beliefs will shape the impact of the Trump and climate cues, with conservative Republicans expected to respond to the Trump and climate cues with more support for Trump actions and liberal Democrats expected to respond with less support. @fig-identity shows the results of the OLS models for cue condition and political beliefs.^[The table of results in shown in the Appendix.]  \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Support by Cue Condition and Political Beliefs](cue-actions_files/figure-docx/fig-identity-1.png){#fig-identity}\n:::\n:::\n\n\nAs shown in @fig-identity, for conservative Republicans, the Trump cue significantly increased their support for opening federal lands to coal leasing and for shortening approval for nuclear power construction. Additionally, support for keeping coal plants open and cancelling the offshore wind projects were significant at _p_<0.10 in the Trump condition. However, the Trump cue did not influence support for eliminating federal tax credits; rather, the climate cue lead to a _decrease_ in support for eliminating the tax credits among conservative Republicans. Otherwise, the climate cue did not have any effects for Republicans, contrary to expectations.  \n\nLiberal Democrats were largely unresponsive to either the Trump cue or the climate cue, compared to those in the control condition. The climate cue reduced support for eliminating the tax credits at _p_<0.10.  \n\nNext, I examine the hypotheses regarding the effect of education and cues. The results are shown in @fig-college. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Support by Trump Cue and College Degree, Conservative Republicans and Liberal Democrats](cue-actions_files/figure-docx/fig-college-1.png){#fig-college}\n:::\n:::\n\n\nAs can be seen, there were no differences in support based on education level, meaning that those without a college degree were no more influenced the Trump cue than those without a degree. This finding held for Republicans and Democrats.^[I also examined the interaction of education and the climate cue. Like the Trump cue, there were no significant difference. The results are shown in the Appendix.]  \n\n\n\nOverall, the clearest evidence is for H1: the Trump cue, but not the climate cue, increased conservative Republican support for four of the five actions (coal leasing and nuclear licensing significantly; keeping coal plants open and cancelling the offshore wind project marginally). There is no reliable evidence that either cue suppressed liberal Democrats' support (H2), or that education moderated the Trump cue's effect on either group (H3, H4). Dropping the Trump-approval control leaves these conclusions materially unchanged.\n\nAs an exploratory check (not preregistered), I also tested whether education moderates the *climate* cue's effect, adding climate.cue:college and its interactions with conRep and libDem to a separate model (@tbl-results-explore). None of these terms approached significance in any of the five models (all *p* > .20), so, unlike the weak evidence for the Trump cue, there is no indication that education conditions the climate cue's effect.\n\n# Discussion and Conclusion\n\nThis paper examined whether a Trump cue and a climate change cue shape public support for five of the second Trump administration's actions on energy, and whether these effects vary by political beliefs and education. Overall, the clearest pattern in the results is that the Trump cue, but not the climate cue, increased support for Trump's actions among conservative Republicans, while liberal Democrats and less-educated respondents were largely unresponsive to either cue.\n\nConsistent with H1, conservative Republicans exposed to the Trump cue were significantly more supportive of opening federal lands to coal leasing and of shortening the regulatory timeline for nuclear power construction, with marginally significant increases in support for keeping coal plants open and cancelling the offshore wind project. This pattern is consistent with the expectation that a cue naming Trump specifically activates expressive and cue-receptive partisanship among Republicans [@mayerPartisanshipPoliticsEnergy2019], and it fits the broader elite cues literature showing that cues from individual political figures, rather than generic partisan cues, are especially likely to move opinion [@nicholsonPolarizingCues2012]. Notably, however, the Trump cue did not increase Republican support for eliminating tax credits for wind and solar projects. One likely explanation is that eliminating tax credits is the only one of the five actions that directly curtails, rather than expands or maintains, an existing energy program, and this difference in the nature of the action may matter more to respondents than the identity of the actor behind it.\n\nThe climate cue produced no significant effects among Republicans for four of the five actions, contrary to expectations. However, it significantly _decreased_ Republican support for eliminating tax credits, the one action in the battery that most directly harms renewable energy deployment. This is likely because the climate cue in this study explicitly named coal, wind, and solar energy and warned that the administration's actions could make climate change worse; for conservative Republicans, this framing may have been credible specifically for an action that curtails renewables, even as it failed to move opinion on the actions involving coal or nuclear. This finding is consistent with research showing that cue and frame effects can depend heavily on how well the cue content matches the specific policy at hand [@feldmanClimateChangePolarizing2018], rather than operating as a uniform, blanket signal across an entire battery of actions.\n\nThere is little support for H2. Liberal Democrats were largely unresponsive to both the Trump cue and the climate cue across the five actions, with only a marginally significant reduction in support for eliminating tax credits under the climate cue. This asymmetry between Republicans' and Democrats' responsiveness is consistent with prior work suggesting that out-group cues do not always produce the backlash that in-group cues produce for co-partisans [@merkleyPartyCuesNews2021], and it may also reflect a ceiling effect: because Democrats' opposition to actions such as coal leasing and tax credit elimination was likely already near the floor of the response scale in the control condition, there was less room for either cue to move their opinions further.\n\nFinally, I find no evidence for H3 or H4. Respondents without a college degree were no more responsive to the Trump cue than those with a degree, and this null result held for both conservative Republicans and liberal Democrats, as well as in an exploratory test of education's interaction with the climate cue. This suggests that, at least in the context of these energy actions, the purported strength of Trump's appeal among white working-class voters [@morganTrumpVotersWhite2018; @abramowitzUnitedStatesRacial2019] did not translate into greater education-based cue receptivity. This null finding is consistent with more recent work questioning whether the white working class was as pivotal, or as distinctive, a component of Trump's coalition as is commonly assumed [@carnesWhiteWorkingClass2021], and it is also consistent with research suggesting that cue receptivity is not simply a function of the cognitive resources associated with lower educational attainment [@bakkerUnderstandingPartisanCue2019].\n\nTogether, these findings suggest that Trump's actions on energy are most likely to further polarize public opinion through their association with Trump himself, rather than through their connection to climate change. This is broadly consistent with the pattern of source-specific polarization described earlier: the actions that showed the clearest Trump cue effects, coal leasing and nuclear licensing, involve energy sources where Republican support was already primed to move [@bergquistEnergyPolicyPublic2020], whereas the tax credit action, which touches wind and solar, showed no Trump cue effect at all. The results also suggest that Trump's influence on energy attitudes operates similarly to his documented effects on other issues, such as immigration and trade policy [@taylorTrumpEffectImmigration2026; @essigTrumpEffectPolitical2021], extending the \"Trump effect\" into the domain of energy policy specifically.\n\nThis study has some limitations. The survey was fielded during a specific and evolving period of the second Trump administration's energy actions, and respondents' reactions to the Trump cue may reflect the cumulative political context at that time rather than a more general and stable response to Trump as a cue-giver. Additionally, the study captures respondents' immediate, single-exposure reactions to the cues, which may not reflect how cue effects accumulate or decay as respondents receive additional information about these actions over time.\n\nFuture research should examine whether the Trump cue effect documented here persists over time and whether it extends to other energy actions beyond the five examined here. Future research should also explore why the climate cue's effects were concentrated on the tax credit action specifically, as this may reveal more general principles about when framing an action's climate implications is more or less persuasive to conservative Republicans.\n\nOverall, this study provides experimental evidence that a cue identifying an energy action as coming from the Trump administration, rather than a cue linking the action to climate change, is the more consistent driver of polarized support for the second Trump administration's approach to energy. As the administration continues to reshape federal energy policy, these results suggest that public reactions to specific actions are likely to be structured more by attitudes toward Trump himself than by their connection to climate change, at least among conservative Republicans.\n\n\\newpage\n\n# Appendix\n\n\n::: {#tbl-results .cell tbl-cap='Weighted OLS Models of Support for Trump\\'s Energy Actions'}\n::: {.cell-output-display}\n\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | Tax Credits | Coal Open | Coal Leasing | Cancel Wind | Nuclear  |\n+==========================+=============+===========+==============+=============+==========+\n| Trump Cue                | -0.035      | -0.074    | -0.115       | -0.037      | -0.306†  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.135)     | (0.141)   | (0.146)      | (0.115)     | (0.166)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate Cue              | 0.320**     | 0.210†    | 0.090        | 0.169       | -0.089   |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.117)     | (0.117)   | (0.112)      | (0.105)     | (0.124)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Cons. Republican         | 1.119***    | 0.968***  | 0.933***     | 1.115***    | 0.555*** |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.133)     | (0.131)   | (0.128)      | (0.130)     | (0.151)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Lib. Democrat            | -0.491***   | -0.649*** | -0.617***    | -0.328***   | -0.376** |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.108)     | (0.114)   | (0.112)      | (0.094)     | (0.134)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| College                  | 0.178       | 0.086     | 0.041        | 0.280*      | 0.315**  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.114)     | (0.113)   | (0.109)      | (0.113)     | (0.114)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x ConRep           | 0.319       | 0.348†    | 0.456*       | 0.348†      | 0.506*   |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.209)     | (0.196)   | (0.202)      | (0.209)     | (0.235)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate x ConRep         | -0.442**    | -0.239    | -0.091       | -0.212      | 0.142    |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.167)     | (0.156)   | (0.158)      | (0.164)     | (0.176)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x LibDem           | -0.067      | -0.068    | -0.071       | -0.130      | -0.155   |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.156)     | (0.166)   | (0.170)      | (0.132)     | (0.204)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate x LibDem         | -0.238†     | -0.170    | -0.077       | -0.147      | 0.098    |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.136)     | (0.138)   | (0.132)      | (0.120)     | (0.153)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x College          | 0.064       | 0.032     | 0.119        | 0.098       | 0.140    |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.191)     | (0.186)   | (0.198)      | (0.183)     | (0.203)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| College x ConRep         | -0.230      | -0.206    | -0.169       | -0.342*     | -0.309†  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.162)     | (0.149)   | (0.152)      | (0.167)     | (0.165)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| College x LibDem         | -0.279*     | -0.161    | -0.172       | -0.410***   | -0.332*  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.130)     | (0.132)   | (0.126)      | (0.124)     | (0.143)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x ConRep x College | -0.414      | -0.096    | -0.184       | -0.401      | -0.053   |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.283)     | (0.258)   | (0.277)      | (0.293)     | (0.290)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x LibDem x College | -0.011      | -0.040    | -0.104       | 0.026       | 0.029    |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.213)     | (0.214)   | (0.222)      | (0.199)     | (0.249)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Intercept                | 1.983***    | 2.342***  | 2.267***     | 1.756***    | 2.911*** |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n|                          | (0.093)     | (0.097)   | (0.093)      | (0.080)     | (0.107)  |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| Num.Obs.                 | 3113        | 3113      | 3113         | 3113        | 3113     |\n+--------------------------+-------------+-----------+--------------+-------------+----------+\n| R2                       | 0.330       | 0.368     | 0.358        | 0.314       | 0.163    |\n+==========================+=============+===========+==============+=============+==========+\n| † p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001                                          |\n+==========================+=============+===========+==============+=============+==========+\n| Survey-weighted OLS (svyglm). Reference categories: control condition, moderate/other      |\n| political identity, no college degree.                                                     |\n+==========================+=============+===========+==============+=============+==========+\n:::\n:::\n\n\n\n::: {#tbl-results-explore .cell tbl-cap='Exploratory Model: Climate Cue x Education (Not Preregistered)'}\n::: {.cell-output-display}\n\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | Tax Credits | Coal Open | Coal Leasing | Cancel Wind | Nuclear  |\n+============================+=============+===========+==============+=============+==========+\n| Trump Cue                  | -0.003      | -0.043    | -0.080       | -0.025      | -0.318†  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.143)     | (0.150)   | (0.154)      | (0.120)     | (0.177)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate Cue                | 0.385*      | 0.273†    | 0.163        | 0.194       | -0.114   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.156)     | (0.156)   | (0.149)      | (0.127)     | (0.172)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Cons. Republican           | 1.104***    | 0.973***  | 0.921***     | 1.093***    | 0.481**  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.149)     | (0.150)   | (0.144)      | (0.144)     | (0.172)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Lib. Democrat              | -0.502***   | -0.627*** | -0.597***    | -0.330**    | -0.424** |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.121)     | (0.130)   | (0.128)      | (0.104)     | (0.155)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| College                    | 0.269†      | 0.174     | 0.141        | 0.315*      | 0.281†   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.151)     | (0.161)   | (0.149)      | (0.158)     | (0.159)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x ConRep             | 0.334       | 0.343     | 0.468*       | 0.370†      | 0.579*   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.219)     | (0.209)   | (0.212)      | (0.218)     | (0.249)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate x ConRep           | -0.419†     | -0.254    | -0.074       | -0.172      | 0.282    |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.221)     | (0.210)   | (0.209)      | (0.209)     | (0.238)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x LibDem             | -0.056      | -0.090    | -0.091       | -0.128      | -0.107   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.165)     | (0.177)   | (0.181)      | (0.140)     | (0.218)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate x LibDem           | -0.222      | -0.216    | -0.120       | -0.144      | 0.191    |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.187)     | (0.190)   | (0.181)      | (0.155)     | (0.215)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x College            | -0.026      | -0.056    | 0.019        | 0.063       | 0.174    |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.215)     | (0.218)   | (0.222)      | (0.214)     | (0.231)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| College x ConRep           | -0.186      | -0.220    | -0.133       | -0.277      | -0.100   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.218)     | (0.213)   | (0.209)      | (0.233)     | (0.235)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| College x LibDem           | -0.263      | -0.227    | -0.234       | -0.408*     | -0.208   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.173)     | (0.186)   | (0.176)      | (0.173)     | (0.202)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x ConRep x College   | -0.459      | -0.082    | -0.220       | -0.465      | -0.262   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.318)     | (0.299)   | (0.312)      | (0.335)     | (0.334)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Trump x LibDem x College   | -0.027      | 0.025     | -0.042       | 0.024       | -0.094   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.241)     | (0.251)   | (0.254)      | (0.233)     | (0.287)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Intercept                  | 1.951***    | 2.310***  | 2.232***     | 1.744***    | 2.923*** |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.104)     | (0.110)   | (0.105)      | (0.086)     | (0.123)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate x College          | -0.191      | -0.186    | -0.212       | -0.074      | 0.072    |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.228)     | (0.224)   | (0.217)      | (0.225)     | (0.229)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate x ConRep x College | -0.075      | 0.040     | -0.058       | -0.123      | -0.418   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.324)     | (0.298)   | (0.303)      | (0.334)     | (0.330)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Climate x LibDem x College | -0.010      | 0.144     | 0.140        | 0.004       | -0.241   |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n|                            | (0.261)     | (0.263)   | (0.253)      | (0.248)     | (0.286)  |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| Num.Obs.                   | 3113        | 3113      | 3113         | 3113        | 3113     |\n+----------------------------+-------------+-----------+--------------+-------------+----------+\n| R2                         | 0.331       | 0.368     | 0.359        | 0.314       | 0.165    |\n+============================+=============+===========+==============+=============+==========+\n| † p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001                                            |\n+============================+=============+===========+==============+=============+==========+\n| Survey-weighted OLS (svyglm). Exploratory model adding climate.cue:college and its           |\n| interactions with conRep/libDem to the preregistered H1-H4 specification; not used for the   |\n| preregistered hypothesis tests.                                                              |\n+============================+=============+===========+==============+=============+==========+\n:::\n:::\n\n\n\\newpage\n\n# References",
    "supporting": [
      "cue-actions_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}